trigger:
- feature/*

pr:
- feature/*

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'

stages:
- stage: SonarCloudAnalysis
  displayName: SonarCloud Analysis Stage

  jobs:
  - job: Analyze
    displayName: Run SonarCloud Analysis

    pool:
      vmImage: $(vmImageName)

    steps:
    - checkout: self
      fetchDepth: 0

    - task: SonarCloudPrepare@4
      displayName: 'Prepare SonarCloud Analysis'
      inputs:
        SonarCloud: 'sdk_sonar'
        organization: 'fastpix'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'FastPix_golang-server-side-language-sdk'
        cliProjectName: 'golang-server-side-language-sdk'
        extraProperties: |
          sonar.projectKey=FastPix_golang-server-side-language-sdk
          sonar.organization=fastpix
          sonar.projectName=golang-server-side-language-sdk
          sonar.sourceEncoding=UTF-8
          sonar.sources=.

    - task: SonarCloudAnalyze@4
      displayName: 'Run SonarCloud Code Analysis'

    - task: SonarCloudPublish@4
      displayName: 'Publish SonarCloud Quality Gate Results'
      inputs:
        pollingTimeoutSec: '300'