/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package fastpixgo

import (
	"bytes"
	"context"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/config"
	"github.com/FastPix/fastpix-go/internal/hooks"
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/models/apierrors"
	"github.com/FastPix/fastpix-go/models/components"
	"github.com/FastPix/fastpix-go/models/operations"
	"github.com/FastPix/fastpix-go/retry"
	"net/http"
	"net/url"
	"time"
)

const errApplyOptions = "error applying option: %w"
const errGeneratingURL = "error generating URL: %w"
const errCreatingRequest = "error creating request: %w"
const UserAgent = "User-Agent"
const errAPIError = "API error occurred"
const ApplicationJson = "application/json"
const errSendingRequest = "error sending request: %w"
const errNoResponse = "error sending request: no response"
const contentType = "Content-Type"
const errUnknownContentType = "unknown content-type received: %s"
const errPopulatingQueryParams = "error populating query params: %w"

type ManageVideos struct {
	rootSDK          *Fastpixgo
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newManageVideos(rootSDK *Fastpixgo, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *ManageVideos {
	return &ManageVideos{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
	}
}

// resolveBaseURL returns the effective base URL from options or SDK config.
func (s *ManageVideos) resolveBaseURL(o operations.Options) string {
	if o.ServerURL != nil {
		return *o.ServerURL
	}
	return utils.ReplaceParameters(s.sdkConfiguration.GetServerDetails())
}

// firstNonNilDuration returns the first non-nil duration, or nil if both are nil.
func firstNonNilDuration(a, b *time.Duration) *time.Duration {
	if a != nil {
		return a
	}
	return b
}

// applyOptions parses the variadic option list into an Options struct.

// resolveRetryConfig returns the effective retry config from options or SDK config.
func (s *ManageVideos) resolveRetryConfig(o operations.Options) *retry.Config {
	if o.Retries != nil {
		return o.Retries
	}
	return s.sdkConfiguration.RetryConfig
}

// prepareRequest sets common headers and security on the request.
func (s *ManageVideos) prepareRequest(ctx context.Context, req *http.Request, o operations.Options) error {
	req.Header.Set("Accept", ApplicationJson)
	req.Header.Set(UserAgent, s.sdkConfiguration.UserAgent)
	if err := utils.PopulateSecurity(ctx, req, s.sdkConfiguration.Security); err != nil {
		return err
	}
	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}
	return nil
}

// retryAttempt is the inner function passed to utils.Retry.
// S3776: extracted from executeRequest to reduce its cognitive complexity.
func (s *ManageVideos) retryAttempt(hookCtx hooks.HookContext, req *http.Request) (*http.Response, error) {
	if req.Body != nil && req.Body != http.NoBody && req.GetBody != nil {
		copyBody, err := req.GetBody()
		if err != nil {
			return nil, err
		}
		req.Body = copyBody
	}
	var err error
	req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
	if err != nil {
		return nil, classifyHookError(err)
	}
	res, doErr := s.sdkConfiguration.Client.Do(req)
	return s.handleDoError(hookCtx, res, doErr)
}


// handleDoError processes the raw result of Client.Do and fires AfterError if needed.
func (s *ManageVideos) handleDoError(hookCtx hooks.HookContext, res *http.Response, doErr error) (*http.Response, error) {
	if doErr != nil {
		doErr = fmt.Errorf(errSendingRequest, doErr)
		_, doErr = s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, nil, doErr)
		return nil, doErr
	}
	if res == nil {
		noRes := fmt.Errorf(errNoResponse)
		_, noRes = s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, nil, noRes)
		return nil, noRes
	}
	return res, nil
}

// executeWithRetry runs the request through utils.Retry then fires AfterSuccess.
func (s *ManageVideos) executeWithRetry(ctx context.Context, hookCtx hooks.HookContext, req *http.Request, retryConfig *retry.Config) (*http.Response, error) {
	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"429", "500", "502", "503", "504"},
	}, func() (*http.Response, error) {
		return s.retryAttempt(hookCtx, req)
	})
	if err != nil {
		return nil, err
	}
	return s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
}

// executeWithoutRetry runs the request once, fires BeforeRequest and handles the response hooks.
func (s *ManageVideos) executeWithoutRetry(hookCtx hooks.HookContext, req *http.Request) (*http.Response, error) {
	var err error
	req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
	if err != nil {
		return nil, err
	}
	res, doErr := s.sdkConfiguration.Client.Do(req)
	if doErr != nil || res == nil {
		return s.handleDoError(hookCtx, res, doErr)
	}
	if utils.MatchStatusCodes([]string{"4XX", "5XX"}, res.StatusCode) {
		altRes, err := s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, res, nil)
		if err != nil {
			return nil, err
		}
		if altRes != nil {
			return altRes, nil
		}
		return res, nil
	}
	return s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, res)
}

// executeRequest dispatches to the retry or non-retry path.
func (s *ManageVideos) executeRequest(ctx context.Context, hookCtx hooks.HookContext, req *http.Request, retryConfig *retry.Config) (*http.Response, error) {
	if retryConfig != nil {
		return s.executeWithRetry(ctx, hookCtx, req, retryConfig)
	}
	return s.executeWithoutRetry(hookCtx, req)
}

// handleUnknownContentType returns an error for an unrecognised Content-Type.
func handleUnknownContentType(httpRes *http.Response) error {
	rawBody, err := utils.ConsumeRawBody(httpRes)
	if err != nil {
		return err
	}
	return apierrors.NewAPIError(fmt.Sprintf(errUnknownContentType, httpRes.Header.Get(contentType)), httpRes.StatusCode, string(rawBody), httpRes)
}

// handleAPIError consumes the body and returns a generic API error.
func handleAPIError(httpRes *http.Response) error {
	rawBody, err := utils.ConsumeRawBody(httpRes)
	if err != nil {
		return err
	}
	return apierrors.NewAPIError(errAPIError, httpRes.StatusCode, string(rawBody), httpRes)
}


// parseJSONBody reads the response body and unmarshals it into out.
func parseJSONBody(httpRes *http.Response, out interface{}) error {
	if !utils.MatchContentType(httpRes.Header.Get(contentType), `application/json`) {
		return handleUnknownContentType(httpRes)
	}
	rawBody, err := utils.ConsumeRawBody(httpRes)
	if err != nil {
		return err
	}
	return utils.UnmarshalJsonFromResponseBody(bytes.NewBuffer(rawBody), out, "")
}

// List - Get list of all media
func (s *ManageVideos) List(ctx context.Context, limit *int64, offset *int64, orderBy *components.SortOrder, opts ...operations.Option) (*operations.ListMediaResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURL(o)
	opURL, err := url.JoinPath(baseURL, "/on-demand")
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "list-media",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := utils.PopulateQueryParams(ctx, req, operations.ListMediaRequest{Limit: limit, Offset: offset, OrderBy: orderBy}, nil, nil); err != nil {
		return nil, fmt.Errorf(errPopulatingQueryParams, err)
	}
	if err := s.prepareRequest(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequest(ctx, hookCtx, req, s.resolveRetryConfig(o))
	if err != nil {
		return nil, err
	}

	res := &operations.ListMediaResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out operations.ListMediaResponseBody
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.Object = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// Delete - Delete a media by ID
func (s *ManageVideos) Delete(ctx context.Context, mediaID string, opts ...operations.Option) (*operations.DeleteMediaResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURL(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/on-demand/{mediaId}", operations.DeleteMediaRequest{MediaID: mediaID}, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "delete-media",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "DELETE", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := s.prepareRequest(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequest(ctx, hookCtx, req, s.resolveRetryConfig(o))
	if err != nil {
		return nil, err
	}

	res := &operations.DeleteMediaResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out operations.DeleteMediaResponseBody
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.Object = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// CancelUpload - Cancel ongoing upload
func (s *ManageVideos) CancelUpload(ctx context.Context, uploadID string, opts ...operations.Option) (*operations.CancelUploadResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURL(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/on-demand/upload/{uploadId}/cancel", operations.CancelUploadRequest{UploadID: uploadID}, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "cancel-upload",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "PUT", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := s.prepareRequest(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequest(ctx, hookCtx, req, s.resolveRetryConfig(o))
	if err != nil {
		return nil, err
	}

	res := &operations.CancelUploadResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out operations.CancelUploadResponseBody
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.Object = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// UpdateTrack - Update audio / subtitle track
func (s *ManageVideos) UpdateTrack(ctx context.Context, trackID string, mediaID string, body components.UpdateTrackRequest, opts ...operations.Option) (*operations.UpdateMediaTrackResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	request := operations.UpdateMediaTrackRequest{TrackID: trackID, MediaID: mediaID, Body: body}
	baseURL := s.resolveBaseURL(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/on-demand/{mediaId}/tracks/{trackId}", request, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "update-media-track",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	bodyReader, mediaType, err := utils.SerializeRequestBody(ctx, request, false, false, "Body", "json", `request:"mediaType=application/json"`)
	if err != nil {
		return nil, err
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "PATCH", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if mediaType != "" {
		req.Header.Set(contentType, mediaType)
	}
	if err := s.prepareRequest(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequest(ctx, hookCtx, req, s.resolveRetryConfig(o))
	if err != nil {
		return nil, err
	}

	res := &operations.UpdateMediaTrackResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out operations.UpdateMediaTrackResponseBody
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.Object = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// GetMediaSummary - Get the summary of a video
func (s *ManageVideos) GetMediaSummary(ctx context.Context, mediaID string, opts ...operations.Option) (*operations.GetMediaSummaryResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURL(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/on-demand/{mediaId}/summary", operations.GetMediaSummaryRequest{MediaID: mediaID}, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "get-media-summary",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := s.prepareRequest(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequest(ctx, hookCtx, req, s.resolveRetryConfig(o))
	if err != nil {
		return nil, err
	}

	res := &operations.GetMediaSummaryResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out operations.GetMediaSummaryResponseBody
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.Object = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// GetInputInfo - Get info of media inputs
func (s *ManageVideos) GetInputInfo(ctx context.Context, mediaID string, opts ...operations.Option) (*operations.RetrieveMediaInputInfoResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURL(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/on-demand/{mediaId}/input-info", operations.RetrieveMediaInputInfoRequest{MediaID: mediaID}, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "retrieveMediaInputInfo",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := s.prepareRequest(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequest(ctx, hookCtx, req, s.resolveRetryConfig(o))
	if err != nil {
		return nil, err
	}

	res := &operations.RetrieveMediaInputInfoResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out operations.RetrieveMediaInputInfoResponseBody
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.Object = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// ListUnusedUploadUrls - Get all unused upload URLs
func (s *ManageVideos) ListUnusedUploadUrls(ctx context.Context, limit *int64, offset *int64, orderBy *components.SortOrder, opts ...operations.Option) (*operations.ListUploadsResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURL(o)
	opURL, err := url.JoinPath(baseURL, "/on-demand/uploads")
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "list-uploads",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := utils.PopulateQueryParams(ctx, req, operations.ListUploadsRequest{Limit: limit, Offset: offset, OrderBy: orderBy}, nil, nil); err != nil {
		return nil, fmt.Errorf(errPopulatingQueryParams, err)
	}
	if err := s.prepareRequest(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequest(ctx, hookCtx, req, s.resolveRetryConfig(o))
	if err != nil {
		return nil, err
	}

	res := &operations.ListUploadsResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out operations.ListUploadsResponseBody
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.Object = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// GenerateSubtitleTrack - Generate track subtitle
func (s *ManageVideos) GenerateSubtitleTrack(ctx context.Context, mediaID string, trackID string, body components.TrackSubtitlesGenerateRequest, opts ...operations.Option) (*operations.GenerateSubtitleTrackResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	request := operations.GenerateSubtitleTrackRequest{MediaID: mediaID, TrackID: trackID, Body: body}
	baseURL := s.resolveBaseURL(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/on-demand/{mediaId}/tracks/{trackId}/generate-subtitles", request, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "Generate-subtitle-track",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	bodyReader, mediaType, err := utils.SerializeRequestBody(ctx, request, false, false, "Body", "json", `request:"mediaType=application/json"`)
	if err != nil {
		return nil, err
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "POST", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if mediaType != "" {
		req.Header.Set(contentType, mediaType)
	}
	if err := s.prepareRequest(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequest(ctx, hookCtx, req, s.resolveRetryConfig(o))
	if err != nil {
		return nil, err
	}

	res := &operations.GenerateSubtitleTrackResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out operations.GenerateSubtitleTrackResponseBody
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.Object = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// GetMediaClips - Get all clips of a media
func (s *ManageVideos) GetMediaClips(ctx context.Context, mediaID string, offset *int64, limit *int64, orderBy *components.SortOrder, opts ...operations.Option) (*operations.GetMediaClipsResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURL(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/on-demand/{mediaId}/media-clips", operations.GetMediaClipsRequest{MediaID: mediaID, Offset: offset, Limit: limit, OrderBy: orderBy}, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "get-media-clips",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := utils.PopulateQueryParams(ctx, req, operations.GetMediaClipsRequest{MediaID: mediaID, Offset: offset, Limit: limit, OrderBy: orderBy}, nil, nil); err != nil {
		return nil, fmt.Errorf(errPopulatingQueryParams, err)
	}
	if err := s.prepareRequest(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequest(ctx, hookCtx, req, s.resolveRetryConfig(o))
	if err != nil {
		return nil, err
	}

	res := &operations.GetMediaClipsResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out components.MediaClipResponse
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.MediaClipResponse = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// resolveBaseURL returns the effective base URL from options or SDK config.