/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package fastpixgo

import (
	"bytes"
	"context"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/config"
	"github.com/FastPix/fastpix-go/internal/hooks"
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/models/components"
	"github.com/FastPix/fastpix-go/models/operations"
	"github.com/FastPix/fastpix-go/retry"
	"net/http"
)

// Playlist - Operations for playlist management
type Playlist struct {
	rootSDK          *Fastpixgo
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newPlaylist(rootSDK *Fastpixgo, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Playlist {
	return &Playlist{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
	}
}

func (s *Playlist) resolveBaseURLPlaylist(o operations.Options) string {
	if o.ServerURL != nil {
		return *o.ServerURL
	}
	return utils.ReplaceParameters(s.sdkConfiguration.GetServerDetails())
}

func (s *Playlist) resolveRetryConfigPlaylist(o operations.Options) *retry.Config {
	if o.Retries != nil {
		return o.Retries
	}
	return s.sdkConfiguration.RetryConfig
}

func (s *Playlist) prepareRequestPlaylist(ctx context.Context, req *http.Request, o operations.Options) error {
	req.Header.Set("Accept", ApplicationJson)
	req.Header.Set(UserAgent, s.sdkConfiguration.UserAgent)
	if err := utils.PopulateSecurity(ctx, req, s.sdkConfiguration.Security); err != nil {
		return err
	}
	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}
	return nil
}

func (s *Playlist) retryAttemptPlaylist(hookCtx hooks.HookContext, req *http.Request) (*http.Response, error) {
	if req.Body != nil && req.Body != http.NoBody && req.GetBody != nil {
		copyBody, err := req.GetBody()
		if err != nil {
			return nil, err
		}
		req.Body = copyBody
	}
	var err error
	req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
	if err != nil {
		return nil, classifyHookError(err)
	}
	res, doErr := s.sdkConfiguration.Client.Do(req)
	return s.handleDoErrorPlaylist(hookCtx, res, doErr)
}

func (s *Playlist) handleDoErrorPlaylist(hookCtx hooks.HookContext, res *http.Response, doErr error) (*http.Response, error) {
	if doErr != nil {
		doErr = fmt.Errorf(errSendingRequest, doErr)
		_, doErr = s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, nil, doErr)
		return nil, doErr
	}
	if res == nil {
		noRes := fmt.Errorf(errNoResponse)
		_, noRes = s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, nil, noRes)
		return nil, noRes
	}
	return res, nil
}

func (s *Playlist) executeWithRetryPlaylist(ctx context.Context, hookCtx hooks.HookContext, req *http.Request, retryConfig *retry.Config) (*http.Response, error) {
	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"429", "500", "502", "503", "504"},
	}, func() (*http.Response, error) {
		return s.retryAttemptPlaylist(hookCtx, req)
	})
	if err != nil {
		return nil, err
	}
	return s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
}

func (s *Playlist) executeWithoutRetryPlaylist(hookCtx hooks.HookContext, req *http.Request) (*http.Response, error) {
	var err error
	req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
	if err != nil {
		return nil, err
	}
	res, doErr := s.sdkConfiguration.Client.Do(req)
	if doErr != nil || res == nil {
		return s.handleDoErrorPlaylist(hookCtx, res, doErr)
	}
	if utils.MatchStatusCodes([]string{"4XX", "5XX"}, res.StatusCode) {
		altRes, err := s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, res, nil)
		if err != nil {
			return nil, err
		}
		if altRes != nil {
			return altRes, nil
		}
		return res, nil
	}
	return s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, res)
}

func (s *Playlist) executeRequestPlaylist(ctx context.Context, hookCtx hooks.HookContext, req *http.Request, retryConfig *retry.Config) (*http.Response, error) {
	if retryConfig != nil {
		return s.executeWithRetryPlaylist(ctx, hookCtx, req, retryConfig)
	}
	return s.executeWithoutRetryPlaylist(hookCtx, req)
}

// parsePlaylistResponse parses a PlaylistByIDResponse from the response body.
// S1871: all 3 methods return PlaylistByIDResponse on 200, so extracted here.
func parsePlaylistResponse(httpRes *http.Response) (*components.PlaylistByIDResponse, error) {
	if !utils.MatchContentType(httpRes.Header.Get(contentType), `application/json`) {
		return nil, handleUnknownContentType(httpRes)
	}
	rawBody, err := utils.ConsumeRawBody(httpRes)
	if err != nil {
		return nil, err
	}
	var out components.PlaylistByIDResponse
	if err := utils.UnmarshalJsonFromResponseBody(bytes.NewBuffer(rawBody), &out, ""); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get - Get a playlist by ID
func (s *Playlist) Get(ctx context.Context, playlistID string, opts ...operations.Option) (*operations.GetPlaylistByIDResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURLPlaylist(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/on-demand/playlists/{playlistId}", operations.GetPlaylistByIDRequest{PlaylistID: playlistID}, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "get-playlist-by-id",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := s.prepareRequestPlaylist(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequestPlaylist(ctx, hookCtx, req, s.resolveRetryConfigPlaylist(o))
	if err != nil {
		return nil, err
	}

	res := &operations.GetPlaylistByIDResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		out, err := parsePlaylistResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.PlaylistByIDResponse = out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// AddMedia - Add media to a playlist by ID
func (s *Playlist) AddMedia(ctx context.Context, playlistID string, body components.MediaIdsRequest, opts ...operations.Option) (*operations.AddMediaToPlaylistResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	request := operations.AddMediaToPlaylistRequest{PlaylistID: playlistID, Body: body}
	baseURL := s.resolveBaseURLPlaylist(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/on-demand/playlists/{playlistId}/media", request, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "add-media-to-playlist",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	bodyReader, mediaType, err := utils.SerializeRequestBody(ctx, request, false, false, "Body", "json", `request:"mediaType=application/json"`)
	if err != nil {
		return nil, err
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "PATCH", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if mediaType != "" {
		req.Header.Set(contentType, mediaType)
	}
	if err := s.prepareRequestPlaylist(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequestPlaylist(ctx, hookCtx, req, s.resolveRetryConfigPlaylist(o))
	if err != nil {
		return nil, err
	}

	res := &operations.AddMediaToPlaylistResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		out, err := parsePlaylistResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.PlaylistByIDResponse = out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// ChangeMediaOrder - Change media order in a playlist by ID
func (s *Playlist) ChangeMediaOrder(ctx context.Context, playlistID string, body components.MediaIdsRequest, opts ...operations.Option) (*operations.ChangeMediaOrderInPlaylistResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	request := operations.ChangeMediaOrderInPlaylistRequest{PlaylistID: playlistID, Body: body}
	baseURL := s.resolveBaseURLPlaylist(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/on-demand/playlists/{playlistId}/media", request, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "change-media-order-in-playlist",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	bodyReader, mediaType, err := utils.SerializeRequestBody(ctx, request, false, false, "Body", "json", `request:"mediaType=application/json"`)
	if err != nil {
		return nil, err
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "PUT", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if mediaType != "" {
		req.Header.Set(contentType, mediaType)
	}
	if err := s.prepareRequestPlaylist(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequestPlaylist(ctx, hookCtx, req, s.resolveRetryConfigPlaylist(o))
	if err != nil {
		return nil, err
	}

	res := &operations.ChangeMediaOrderInPlaylistResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		out, err := parsePlaylistResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.PlaylistByIDResponse = out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}
