/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package fastpixgo

import (
	"context"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/config"
	"github.com/FastPix/fastpix-go/internal/hooks"
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/models/components"
	"github.com/FastPix/fastpix-go/models/operations"
	"github.com/FastPix/fastpix-go/retry"
	"net/http"
	"net/url"
)

type SigningKeys struct {
	rootSDK          *Fastpixgo
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newSigningKeys(rootSDK *Fastpixgo, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *SigningKeys {
	return &SigningKeys{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
	}
}

func (s *SigningKeys) resolveBaseURLSigningKeys(o operations.Options) string {
	if o.ServerURL != nil {
		return *o.ServerURL
	}
	return utils.ReplaceParameters(s.sdkConfiguration.GetServerDetails())
}

func (s *SigningKeys) resolveRetryConfigSigningKeys(o operations.Options) *retry.Config {
	if o.Retries != nil {
		return o.Retries
	}
	return s.sdkConfiguration.RetryConfig
}

func (s *SigningKeys) prepareRequestSigningKeys(ctx context.Context, req *http.Request, o operations.Options) error {
	req.Header.Set("Accept", ApplicationJson)
	req.Header.Set(UserAgent, s.sdkConfiguration.UserAgent)
	if err := utils.PopulateSecurity(ctx, req, s.sdkConfiguration.Security); err != nil {
		return err
	}
	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}
	return nil
}

func (s *SigningKeys) retryAttemptSigningKeys(hookCtx hooks.HookContext, req *http.Request) (*http.Response, error) {
	if req.Body != nil && req.Body != http.NoBody && req.GetBody != nil {
		copyBody, err := req.GetBody()
		if err != nil {
			return nil, err
		}
		req.Body = copyBody
	}
	var err error
	req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
	if err != nil {
		return nil, classifyHookError(err)
	}
	res, doErr := s.sdkConfiguration.Client.Do(req)
	return s.handleDoErrorSigningKeys(hookCtx, res, doErr)
}

func (s *SigningKeys) handleDoErrorSigningKeys(hookCtx hooks.HookContext, res *http.Response, doErr error) (*http.Response, error) {
	if doErr != nil {
		doErr = fmt.Errorf(errSendingRequest, doErr)
		_, doErr = s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, nil, doErr)
		return nil, doErr
	}
	if res == nil {
		noRes := fmt.Errorf(errNoResponse)
		_, noRes = s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, nil, noRes)
		return nil, noRes
	}
	return res, nil
}

func (s *SigningKeys) executeWithRetrySigningKeys(ctx context.Context, hookCtx hooks.HookContext, req *http.Request, retryConfig *retry.Config) (*http.Response, error) {
	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"429", "500", "502", "503", "504"},
	}, func() (*http.Response, error) {
		return s.retryAttemptSigningKeys(hookCtx, req)
	})
	if err != nil {
		return nil, err
	}
	return s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
}

func (s *SigningKeys) executeWithoutRetrySigningKeys(hookCtx hooks.HookContext, req *http.Request) (*http.Response, error) {
	var err error
	req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
	if err != nil {
		return nil, err
	}
	res, doErr := s.sdkConfiguration.Client.Do(req)
	if doErr != nil || res == nil {
		return s.handleDoErrorSigningKeys(hookCtx, res, doErr)
	}
	if utils.MatchStatusCodes([]string{"4XX", "5XX"}, res.StatusCode) {
		altRes, err := s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, res, nil)
		if err != nil {
			return nil, err
		}
		if altRes != nil {
			return altRes, nil
		}
		return res, nil
	}
	return s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, res)
}

func (s *SigningKeys) executeRequestSigningKeys(ctx context.Context, hookCtx hooks.HookContext, req *http.Request, retryConfig *retry.Config) (*http.Response, error) {
	if retryConfig != nil {
		return s.executeWithRetrySigningKeys(ctx, hookCtx, req, retryConfig)
	}
	return s.executeWithoutRetrySigningKeys(hookCtx, req)
}

// Create - Create a signing key
func (s *SigningKeys) Create(ctx context.Context, opts ...operations.Option) (*operations.CreateSigningKeyResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURLSigningKeys(o)
	opURL, err := url.JoinPath(baseURL, "/iam/signing-keys")
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "create_signing_key",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "POST", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := s.prepareRequestSigningKeys(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequestSigningKeys(ctx, hookCtx, req, s.resolveRetryConfigSigningKeys(o))
	if err != nil {
		return nil, err
	}

	res := &operations.CreateSigningKeyResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 201:
		var out components.CreateResponse
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.CreateResponse = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// List - Get list of signing keys
func (s *SigningKeys) List(ctx context.Context, limit *int64, offset *int64, opts ...operations.Option) (*operations.ListSigningKeysResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURLSigningKeys(o)
	opURL, err := url.JoinPath(baseURL, "/iam/signing-keys")
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "list_signing_keys",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := utils.PopulateQueryParams(ctx, req, operations.ListSigningKeysRequest{Limit: limit, Offset: offset}, nil, nil); err != nil {
		return nil, fmt.Errorf(errPopulatingQueryParams, err)
	}
	if err := s.prepareRequestSigningKeys(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequestSigningKeys(ctx, hookCtx, req, s.resolveRetryConfigSigningKeys(o))
	if err != nil {
		return nil, err
	}

	res := &operations.ListSigningKeysResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out components.GetAllSigningKeysResponse
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.GetAllSigningKeysResponse = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// Delete - Delete a signing key
func (s *SigningKeys) Delete(ctx context.Context, signingKeyID string, opts ...operations.Option) (*operations.DeleteSigningKeyResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURLSigningKeys(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/iam/signing-keys/{signingKeyId}", operations.DeleteSigningKeyRequest{SigningKeyID: signingKeyID}, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "delete_signing_key",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "DELETE", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := s.prepareRequestSigningKeys(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequestSigningKeys(ctx, hookCtx, req, s.resolveRetryConfigSigningKeys(o))
	if err != nil {
		return nil, err
	}

	res := &operations.DeleteSigningKeyResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out components.DeleteSigningKeyResponse
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.DeleteSigningKeyResponse = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}

// GetByID - Get signing key by ID
func (s *SigningKeys) GetByID(ctx context.Context, signingKeyID string, opts ...operations.Option) (*operations.GetSigningKeyByIDResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURLSigningKeys(o)
	opURL, err := utils.GenerateURL(ctx, baseURL, "/iam/signing-keys/{signingKeyId}", operations.GetSigningKeyByIDRequest{SigningKeyID: signingKeyID}, nil)
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "get-signing_key_by_id",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, nil)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if err := s.prepareRequestSigningKeys(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequestSigningKeys(ctx, hookCtx, req, s.resolveRetryConfigSigningKeys(o))
	if err != nil {
		return nil, err
	}

	res := &operations.GetSigningKeyByIDResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 200:
		var out components.GetPublicPemUsingSigningKeyIDResponseDTO
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.GetPublicPemUsingSigningKeyIDResponseDTO = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}