/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package fastpixgo

import (
	"context"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/config"
	"github.com/FastPix/fastpix-go/internal/hooks"
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/models/components"
	"github.com/FastPix/fastpix-go/models/operations"
	"github.com/FastPix/fastpix-go/retry"
	"net/http"
	"net/url"
)

type StartLiveStream struct {
	rootSDK          *Fastpixgo
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newStartLiveStream(rootSDK *Fastpixgo, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *StartLiveStream {
	return &StartLiveStream{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
	}
}

func (s *StartLiveStream) resolveBaseURLStartLiveStream(o operations.Options) string {
	if o.ServerURL != nil {
		return *o.ServerURL
	}
	return utils.ReplaceParameters(s.sdkConfiguration.GetServerDetails())
}

func (s *StartLiveStream) resolveRetryConfigStartLiveStream(o operations.Options) *retry.Config {
	if o.Retries != nil {
		return o.Retries
	}
	return s.sdkConfiguration.RetryConfig
}

func (s *StartLiveStream) prepareRequestStartLiveStream(ctx context.Context, req *http.Request, o operations.Options) error {
	req.Header.Set("Accept", ApplicationJson)
	req.Header.Set(UserAgent, s.sdkConfiguration.UserAgent)
	if err := utils.PopulateSecurity(ctx, req, s.sdkConfiguration.Security); err != nil {
		return err
	}
	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}
	return nil
}

func (s *StartLiveStream) retryAttemptStartLiveStream(hookCtx hooks.HookContext, req *http.Request) (*http.Response, error) {
	if req.Body != nil && req.Body != http.NoBody && req.GetBody != nil {
		copyBody, err := req.GetBody()
		if err != nil {
			return nil, err
		}
		req.Body = copyBody
	}
	var err error
	req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
	if err != nil {
		return nil, classifyHookError(err)
	}
	res, doErr := s.sdkConfiguration.Client.Do(req)
	return s.handleDoErrorStartLiveStream(hookCtx, res, doErr)
}

func (s *StartLiveStream) handleDoErrorStartLiveStream(hookCtx hooks.HookContext, res *http.Response, doErr error) (*http.Response, error) {
	if doErr != nil {
		doErr = fmt.Errorf(errSendingRequest, doErr)
		_, doErr = s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, nil, doErr)
		return nil, doErr
	}
	if res == nil {
		noRes := fmt.Errorf(errNoResponse)
		_, noRes = s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, nil, noRes)
		return nil, noRes
	}
	return res, nil
}

func (s *StartLiveStream) executeWithRetryStartLiveStream(ctx context.Context, hookCtx hooks.HookContext, req *http.Request, retryConfig *retry.Config) (*http.Response, error) {
	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"429", "500", "502", "503", "504"},
	}, func() (*http.Response, error) {
		return s.retryAttemptStartLiveStream(hookCtx, req)
	})
	if err != nil {
		return nil, err
	}
	return s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
}

func (s *StartLiveStream) executeWithoutRetryStartLiveStream(hookCtx hooks.HookContext, req *http.Request) (*http.Response, error) {
	var err error
	req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
	if err != nil {
		return nil, err
	}
	res, doErr := s.sdkConfiguration.Client.Do(req)
	if doErr != nil || res == nil {
		return s.handleDoErrorStartLiveStream(hookCtx, res, doErr)
	}
	if utils.MatchStatusCodes([]string{"4XX", "5XX"}, res.StatusCode) {
		altRes, err := s.hooks.AfterError(hooks.AfterErrorContext{HookContext: hookCtx}, res, nil)
		if err != nil {
			return nil, err
		}
		if altRes != nil {
			return altRes, nil
		}
		return res, nil
	}
	return s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, res)
}

func (s *StartLiveStream) executeRequestStartLiveStream(ctx context.Context, hookCtx hooks.HookContext, req *http.Request, retryConfig *retry.Config) (*http.Response, error) {
	if retryConfig != nil {
		return s.executeWithRetryStartLiveStream(ctx, hookCtx, req, retryConfig)
	}
	return s.executeWithoutRetryStartLiveStream(hookCtx, req)
}

// Create - Create a new stream
func (s *StartLiveStream) Create(ctx context.Context, request components.CreateLiveStreamRequest, opts ...operations.Option) (*operations.CreateNewStreamResponse, error) {
	o, err := applyOptions(opts)
	if err != nil {
		return nil, err
	}

	baseURL := s.resolveBaseURLStartLiveStream(o)
	opURL, err := url.JoinPath(baseURL, "/live/streams")
	if err != nil {
		return nil, fmt.Errorf(errGeneratingURL, err)
	}

	hookCtx := hooks.HookContext{
		SDK: s.rootSDK, SDKConfiguration: s.sdkConfiguration,
		BaseURL: baseURL, Context: ctx, OperationID: "create-new-stream",
		OAuth2Scopes: nil, SecuritySource: s.sdkConfiguration.Security,
	}

	bodyReader, mediaType, err := utils.SerializeRequestBody(ctx, request, false, false, "Request", "json", `request:"mediaType=application/json"`)
	if err != nil {
		return nil, err
	}

	if t := firstNonNilDuration(o.Timeout, s.sdkConfiguration.Timeout); t != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *t)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "POST", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf(errCreatingRequest, err)
	}
	if mediaType != "" {
		req.Header.Set(contentType, mediaType)
	}
	if err := s.prepareRequestStartLiveStream(ctx, req, o); err != nil {
		return nil, err
	}

	httpRes, err := s.executeRequestStartLiveStream(ctx, hookCtx, req, s.resolveRetryConfigStartLiveStream(o))
	if err != nil {
		return nil, err
	}

	res := &operations.CreateNewStreamResponse{HTTPMeta: components.HTTPMetadata{Request: req, Response: httpRes}}
	switch {
	case httpRes.StatusCode == 201:
		var out components.LiveStreamResponseDTO
		if err := parseJSONBody(httpRes, &out); err != nil {
			return nil, err
		}
		res.LiveStreamResponseDTO = &out
	case httpRes.StatusCode >= 400 && httpRes.StatusCode < 600:
		return nil, handleAPIError(httpRes)
	default:
		defaultErr, err := parseDefaultResponse(httpRes)
		if err != nil {
			return nil, err
		}
		res.DefaultError = defaultErr
	}
	return res, nil
}
