/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package operations

import (
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/models/components"
)

type CreateNewStreamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Stream created successfully
	LiveStreamResponseDTO *components.LiveStreamResponseDTO
	// See the range of possible <a href="https://docs.fastpix.io/reference/error-codes">error</a> responses and their status codes.
	DefaultError *components.DefaultError
}

func (c CreateNewStreamResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateNewStreamResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateNewStreamResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateNewStreamResponse) GetLiveStreamResponseDTO() *components.LiveStreamResponseDTO {
	if c == nil {
		return nil
	}
	return c.LiveStreamResponseDTO
}

func (c *CreateNewStreamResponse) GetDefaultError() *components.DefaultError {
	if c == nil {
		return nil
	}
	return c.DefaultError
}
