// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/FastPix/fastpix-go/models/components"
)

type CreatePlaybackIDOfStreamRequest struct {
	// Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
	StreamID          string                        `pathParam:"style=simple,explode=false,name=streamId"`
	PlaybackIDRequest *components.PlaybackIDRequest `request:"mediaType=application/json"`
}

func (o *CreatePlaybackIDOfStreamRequest) GetStreamID() string {
	if o == nil {
		return ""
	}
	return o.StreamID
}

func (o *CreatePlaybackIDOfStreamRequest) GetPlaybackIDRequest() *components.PlaybackIDRequest {
	if o == nil {
		return nil
	}
	return o.PlaybackIDRequest
}

type CreatePlaybackIDOfStreamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// New PlaybackId created successfully
	PlaybackIDResponse *components.PlaybackIDResponse
}

func (o *CreatePlaybackIDOfStreamResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreatePlaybackIDOfStreamResponse) GetPlaybackIDResponse() *components.PlaybackIDResponse {
	if o == nil {
		return nil
	}
	return o.PlaybackIDResponse
}
