/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package operations

import (
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/models/components"
)

type CreatePlaybackIDOfStreamRequest struct {
	// After creating a new live stream, FastPix assigns a unique identifier to the stream.
	StreamID string                       `pathParam:"style=simple,explode=false,name=streamId"`
	Body     components.PlaybackIDRequest `request:"mediaType=application/json"`
}

func (c *CreatePlaybackIDOfStreamRequest) GetStreamID() string {
	if c == nil {
		return ""
	}
	return c.StreamID
}

func (c *CreatePlaybackIDOfStreamRequest) GetBody() components.PlaybackIDRequest {
	if c == nil {
		return components.PlaybackIDRequest{}
	}
	return c.Body
}

type CreatePlaybackIDOfStreamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// New PlaybackId created successfully
	PlaybackIDSuccessResponse *components.PlaybackIDSuccessResponse
	// See the range of possible <a href="https://docs.fastpix.io/reference/error-codes">error</a> responses and their status codes.
	DefaultError *components.DefaultError
}

func (c CreatePlaybackIDOfStreamResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePlaybackIDOfStreamResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePlaybackIDOfStreamResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreatePlaybackIDOfStreamResponse) GetPlaybackIDSuccessResponse() *components.PlaybackIDSuccessResponse {
	if c == nil {
		return nil
	}
	return c.PlaybackIDSuccessResponse
}

func (c *CreatePlaybackIDOfStreamResponse) GetDefaultError() *components.DefaultError {
	if c == nil {
		return nil
	}
	return c.DefaultError
}
