/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/models/components"
)

// DirectUploadVideoMediaAccessPolicy - Determines if access to the streamed content is kept private, drm or available to all.
type DirectUploadVideoMediaAccessPolicy string

const (
	DirectUploadVideoMediaAccessPolicyPublic  DirectUploadVideoMediaAccessPolicy = "public"
	DirectUploadVideoMediaAccessPolicyPrivate DirectUploadVideoMediaAccessPolicy = "private"
	DirectUploadVideoMediaAccessPolicyDrm     DirectUploadVideoMediaAccessPolicy = "drm"
)

func (e DirectUploadVideoMediaAccessPolicy) ToPointer() *DirectUploadVideoMediaAccessPolicy {
	return &e
}
func (e *DirectUploadVideoMediaAccessPolicy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "public":
		fallthrough
	case "private":
		fallthrough
	case "drm":
		*e = DirectUploadVideoMediaAccessPolicy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DirectUploadVideoMediaAccessPolicy: %v", v)
	}
}

type InputType string

const (
	InputTypeVideoInput     InputType = "VideoInput"
	InputTypeWatermarkInput InputType = "WatermarkInput"
	InputTypeAudioInput     InputType = "AudioInput"
	InputTypeSubtitleInput  InputType = "SubtitleInput"
)

type Input struct {
	VideoInput     *components.VideoInput     `queryParam:"inline" union:"member"`
	WatermarkInput *components.WatermarkInput `queryParam:"inline" union:"member"`
	AudioInput     *components.AudioInput     `queryParam:"inline" union:"member"`
	SubtitleInput  *components.SubtitleInput  `queryParam:"inline" union:"member"`

	Type InputType
}

func CreateInputVideoInput(videoInput components.VideoInput) Input {
	typ := InputTypeVideoInput

	return Input{
		VideoInput: &videoInput,
		Type:       typ,
	}
}

func CreateInputWatermarkInput(watermarkInput components.WatermarkInput) Input {
	typ := InputTypeWatermarkInput

	return Input{
		WatermarkInput: &watermarkInput,
		Type:           typ,
	}
}

func CreateInputAudioInput(audioInput components.AudioInput) Input {
	typ := InputTypeAudioInput

	return Input{
		AudioInput: &audioInput,
		Type:       typ,
	}
}

func CreateInputSubtitleInput(subtitleInput components.SubtitleInput) Input {
	typ := InputTypeSubtitleInput

	return Input{
		SubtitleInput: &subtitleInput,
		Type:          typ,
	}
}

func (u *Input) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var videoInput components.VideoInput = components.VideoInput{}
	if err := utils.UnmarshalJSON(data, &videoInput, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InputTypeVideoInput,
			Value: &videoInput,
		})
	}

	var watermarkInput components.WatermarkInput = components.WatermarkInput{}
	if err := utils.UnmarshalJSON(data, &watermarkInput, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InputTypeWatermarkInput,
			Value: &watermarkInput,
		})
	}

	var audioInput components.AudioInput = components.AudioInput{}
	if err := utils.UnmarshalJSON(data, &audioInput, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InputTypeAudioInput,
			Value: &audioInput,
		})
	}

	var subtitleInput components.SubtitleInput = components.SubtitleInput{}
	if err := utils.UnmarshalJSON(data, &subtitleInput, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  InputTypeSubtitleInput,
			Value: &subtitleInput,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Input", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Input", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(InputType)
	switch best.Type {
	case InputTypeVideoInput:
		u.VideoInput = best.Value.(*components.VideoInput)
		return nil
	case InputTypeWatermarkInput:
		u.WatermarkInput = best.Value.(*components.WatermarkInput)
		return nil
	case InputTypeAudioInput:
		u.AudioInput = best.Value.(*components.AudioInput)
		return nil
	case InputTypeSubtitleInput:
		u.SubtitleInput = best.Value.(*components.SubtitleInput)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Input", string(data))
}

func (u Input) MarshalJSON() ([]byte, error) {
	if u.VideoInput != nil {
		return utils.MarshalJSON(u.VideoInput, "", true)
	}

	if u.WatermarkInput != nil {
		return utils.MarshalJSON(u.WatermarkInput, "", true)
	}

	if u.AudioInput != nil {
		return utils.MarshalJSON(u.AudioInput, "", true)
	}

	if u.SubtitleInput != nil {
		return utils.MarshalJSON(u.SubtitleInput, "", true)
	}

	return nil, errors.New("could not marshal union type Input: all fields are null")
}

// LanguageCode - Language codes (BCP 47 compliant) used for text files.
type LanguageCode string

const (
	LanguageCodeEn LanguageCode = "en"
	LanguageCodeIt LanguageCode = "it"
	LanguageCodePl LanguageCode = "pl"
	LanguageCodeEs LanguageCode = "es"
	LanguageCodeFr LanguageCode = "fr"
	LanguageCodeRu LanguageCode = "ru"
	LanguageCodeNl LanguageCode = "nl"
)

func (e LanguageCode) ToPointer() *LanguageCode {
	return &e
}
func (e *LanguageCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "en":
		fallthrough
	case "it":
		fallthrough
	case "pl":
		fallthrough
	case "es":
		fallthrough
	case "fr":
		fallthrough
	case "ru":
		fallthrough
	case "nl":
		*e = LanguageCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LanguageCode: %v", v)
	}
}

// Subtitles - Generates subtitle files for audio/video files.
type Subtitles struct {
	// Name of the language for the subtitles.
	LanguageName *string `json:"languageName,omitzero"`
	// "Tag a video in "key" : "value" pairs for searchable metadata. Maximum 10 entries, 255 characters each."
	//
	Metadata map[string]string `json:"metadata,omitzero"`
	// Language codes (BCP 47 compliant) used for text files.
	//
	LanguageCode *LanguageCode `json:"languageCode,omitzero"`
}

func (s Subtitles) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Subtitles) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Subtitles) GetLanguageName() *string {
	if s == nil {
		return nil
	}
	return s.LanguageName
}

func (s *Subtitles) GetMetadata() map[string]string {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *Subtitles) GetLanguageCode() *LanguageCode {
	if s == nil {
		return nil
	}
	return s.LanguageCode
}

// MaxResolution - Determines the highest quality resolution available.
type MaxResolution string

const (
	MaxResolutionTwoThousandOneHundredAndSixtyp  MaxResolution = "2160p"
	MaxResolutionOneThousandFourHundredAndFortyp MaxResolution = "1440p"
	MaxResolutionOneThousandAndEightyp           MaxResolution = "1080p"
	MaxResolutionSevenHundredAndTwentyp          MaxResolution = "720p"
	MaxResolutionFourHundredAndEightyp           MaxResolution = "480p"
)

func (e MaxResolution) ToPointer() *MaxResolution {
	return &e
}
func (e *MaxResolution) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "2160p":
		fallthrough
	case "1440p":
		fallthrough
	case "1080p":
		fallthrough
	case "720p":
		fallthrough
	case "480p":
		*e = MaxResolution(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MaxResolution: %v", v)
	}
}

// MediaQuality - The quality tier applied to the media.
type MediaQuality string

const (
	MediaQualityStandard MediaQuality = "standard"
	MediaQualityPro      MediaQuality = "pro"
	MediaQualityPremium  MediaQuality = "premium"
)

func (e MediaQuality) ToPointer() *MediaQuality {
	return &e
}
func (e *MediaQuality) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "standard":
		fallthrough
	case "pro":
		fallthrough
	case "premium":
		*e = MediaQuality(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MediaQuality: %v", v)
	}
}

// DirectUploadVideoMediaMp4Support - Generates MP4 video up to 4K ("capped_4k"), m4a audio only ("audioOnly"), or both for offline viewing.
type DirectUploadVideoMediaMp4Support string

const (
	DirectUploadVideoMediaMp4SupportCapped4k          DirectUploadVideoMediaMp4Support = "capped_4k"
	DirectUploadVideoMediaMp4SupportAudioOnly         DirectUploadVideoMediaMp4Support = "audioOnly"
	DirectUploadVideoMediaMp4SupportAudioOnlyCapped4k DirectUploadVideoMediaMp4Support = "audioOnly,capped_4k"
)

func (e DirectUploadVideoMediaMp4Support) ToPointer() *DirectUploadVideoMediaMp4Support {
	return &e
}
func (e *DirectUploadVideoMediaMp4Support) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "capped_4k":
		fallthrough
	case "audioOnly":
		fallthrough
	case "audioOnly,capped_4k":
		*e = DirectUploadVideoMediaMp4Support(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DirectUploadVideoMediaMp4Support: %v", v)
	}
}

type Summary struct {
	// Enable or disable the summary feature for the media. Set to true to enable summary or false to disable.
	//
	Generate *bool `json:"generate,omitzero"`
	// Specifies the desired word count for the generated summary.
	// - The value must be between **30** and **250** words.
	//
	SummaryLength *int64 `json:"summaryLength,omitzero"`
}

func (s *Summary) GetGenerate() *bool {
	if s == nil {
		return nil
	}
	return s.Generate
}

func (s *Summary) GetSummaryLength() *int64 {
	if s == nil {
		return nil
	}
	return s.SummaryLength
}

// Type - Defines the type of input. Possible values include video, audio, av.
type Type string

const (
	TypeVideo Type = "video"
	TypeAudio Type = "audio"
	TypeAv    Type = "av"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "video":
		fallthrough
	case "audio":
		fallthrough
	case "av":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type DirectUploadVideoMediaModeration struct {
	// Defines the type of input. Possible values include video, audio, av.
	//
	Type *Type `json:"type,omitzero"`
}

func (d *DirectUploadVideoMediaModeration) GetType() *Type {
	if d == nil {
		return nil
	}
	return d.Type
}

// DirectUploadVideoMediaDomainsDefaultPolicy - Specifies the default access policy for domains.
// If set to `allow`, all domains are allowed access unless otherwise specified in the `deny` list.
// If set to `deny`, all domains are denied access unless otherwise specified in the `allow` list.
type DirectUploadVideoMediaDomainsDefaultPolicy string

const (
	DirectUploadVideoMediaDomainsDefaultPolicyAllow DirectUploadVideoMediaDomainsDefaultPolicy = "allow"
	DirectUploadVideoMediaDomainsDefaultPolicyDeny  DirectUploadVideoMediaDomainsDefaultPolicy = "deny"
)

func (e DirectUploadVideoMediaDomainsDefaultPolicy) ToPointer() *DirectUploadVideoMediaDomainsDefaultPolicy {
	return &e
}
func (e *DirectUploadVideoMediaDomainsDefaultPolicy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "allow":
		fallthrough
	case "deny":
		*e = DirectUploadVideoMediaDomainsDefaultPolicy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DirectUploadVideoMediaDomainsDefaultPolicy: %v", v)
	}
}

type DirectUploadVideoMediaDomains struct {
	// Specifies the default access policy for domains.
	// If set to `allow`, all domains are allowed access unless otherwise specified in the `deny` list.
	// If set to `deny`, all domains are denied access unless otherwise specified in the `allow` list.
	//
	DefaultPolicy *DirectUploadVideoMediaDomainsDefaultPolicy `json:"defaultPolicy,omitzero"`
	// A list of domain names or patterns that are explicitly allowed access.
	// This list is only effective when the `defaultPolicy` is set to `deny`.
	//
	Allow []string `json:"allow,omitzero"`
	// A list of domain names or patterns that are explicitly denied access.
	// This list is only effective when the `defaultPolicy` is set to `allow`.
	//
	Deny []string `json:"deny,omitzero"`
}

func (d DirectUploadVideoMediaDomains) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DirectUploadVideoMediaDomains) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DirectUploadVideoMediaDomains) GetDefaultPolicy() *DirectUploadVideoMediaDomainsDefaultPolicy {
	if d == nil {
		return nil
	}
	return d.DefaultPolicy
}

func (d *DirectUploadVideoMediaDomains) GetAllow() []string {
	if d == nil {
		return nil
	}
	return d.Allow
}

func (d *DirectUploadVideoMediaDomains) GetDeny() []string {
	if d == nil {
		return nil
	}
	return d.Deny
}

// DirectUploadVideoMediaUserAgentsDefaultPolicy - Specifies the default access policy for user agents (browsers, bots, etc.).
// If set to `allow`, all user agents are allowed access unless otherwise specified in the `deny` list.
// If set to `deny`, all user agents are denied access unless otherwise specified in the `allow` list.
type DirectUploadVideoMediaUserAgentsDefaultPolicy string

const (
	DirectUploadVideoMediaUserAgentsDefaultPolicyAllow DirectUploadVideoMediaUserAgentsDefaultPolicy = "allow"
	DirectUploadVideoMediaUserAgentsDefaultPolicyDeny  DirectUploadVideoMediaUserAgentsDefaultPolicy = "deny"
)

func (e DirectUploadVideoMediaUserAgentsDefaultPolicy) ToPointer() *DirectUploadVideoMediaUserAgentsDefaultPolicy {
	return &e
}
func (e *DirectUploadVideoMediaUserAgentsDefaultPolicy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "allow":
		fallthrough
	case "deny":
		*e = DirectUploadVideoMediaUserAgentsDefaultPolicy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DirectUploadVideoMediaUserAgentsDefaultPolicy: %v", v)
	}
}

type DirectUploadVideoMediaUserAgents struct {
	// Specifies the default access policy for user agents (browsers, bots, etc.).
	// If set to `allow`, all user agents are allowed access unless otherwise specified in the `deny` list.
	// If set to `deny`, all user agents are denied access unless otherwise specified in the `allow` list.
	//
	DefaultPolicy *DirectUploadVideoMediaUserAgentsDefaultPolicy `json:"defaultPolicy,omitzero"`
	// A list of user agents (identified by string names or patterns) that are explicitly allowed access.
	// This list is only effective when the `defaultPolicy` is set to `deny`.
	//
	Allow []string `json:"allow,omitzero"`
	// A list of user agents (identified by string names or patterns) that are explicitly denied access.
	// This list is only effective when the `defaultPolicy` is set to `allow`.
	//
	Deny []string `json:"deny,omitzero"`
}

func (d DirectUploadVideoMediaUserAgents) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DirectUploadVideoMediaUserAgents) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DirectUploadVideoMediaUserAgents) GetDefaultPolicy() *DirectUploadVideoMediaUserAgentsDefaultPolicy {
	if d == nil {
		return nil
	}
	return d.DefaultPolicy
}

func (d *DirectUploadVideoMediaUserAgents) GetAllow() []string {
	if d == nil {
		return nil
	}
	return d.Allow
}

func (d *DirectUploadVideoMediaUserAgents) GetDeny() []string {
	if d == nil {
		return nil
	}
	return d.Deny
}

type DirectUploadVideoMediaAccessRestrictions struct {
	Domains    *DirectUploadVideoMediaDomains    `json:"domains,omitzero"`
	UserAgents *DirectUploadVideoMediaUserAgents `json:"userAgents,omitzero"`
}

func (d DirectUploadVideoMediaAccessRestrictions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DirectUploadVideoMediaAccessRestrictions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DirectUploadVideoMediaAccessRestrictions) GetDomains() *DirectUploadVideoMediaDomains {
	if d == nil {
		return nil
	}
	return d.Domains
}

func (d *DirectUploadVideoMediaAccessRestrictions) GetUserAgents() *DirectUploadVideoMediaUserAgents {
	if d == nil {
		return nil
	}
	return d.UserAgents
}

// PushMediaSettings - Configuration settings for uploading and processing media on the FastPix platform.
// These settings define how the uploaded video is handled, including access control, resolution, DRM, and optional metadata.
// For a complete explanation of how media uploads and processing work, refer to the
// <a href="https://docs.fastpix.io/docs/video-on-demand-overview" target="_blank">FastPix Video on Demand Overview</a>.
type PushMediaSettings struct {
	// Determines if access to the streamed content is kept private, drm or available to all.
	AccessPolicy *DirectUploadVideoMediaAccessPolicy `default:"public" json:"accessPolicy"`
	// Start time indicates where encoding must begin within the video file, in seconds.
	StartTime *float64 `json:"startTime,omitzero"`
	// End time indicates where encoding must end within the video file, in seconds.
	EndTime *float64 `json:"endTime,omitzero"`
	// Add one input object at a time. For example, first add a **WatermarkInput** object.   If you also need a audio, click **Add item** again and select **AudioInput**.   Repeat this process for **SubtitleInput** as needed.
	//
	Inputs []Input `json:"inputs,omitzero"`
	// "Tag a video in "key" : "value" pairs for searchable metadata. Maximum 10 entries, 255 characters each."
	//
	Metadata map[string]string `json:"metadata,omitzero"`
	// UUID of the DRM configuration to be used.
	DrmConfigurationID *string `json:"drmConfigurationId,omitzero"`
	// Title of the media file.
	Title *string `json:"title,omitzero"`
	// The unique identifier of the user who created this media.
	CreatorID *string `json:"creatorId,omitzero"`
	// Generates subtitle files for audio/video files.
	//
	Subtitles *Subtitles `json:"subtitles,omitzero"`
	// Enhance the quality and volume of the audio track. This is available for pre-recorded content only.
	//
	OptimizeAudio *bool `json:"optimizeAudio,omitzero"`
	// Determines the highest quality resolution available.
	//
	MaxResolution *MaxResolution `default:"1080p" json:"maxResolution"`
	// The quality tier applied to the media.
	MediaQuality *MediaQuality `default:"standard" json:"mediaQuality"`
	// The sourceAccess parameter determines whether the original media file is accessible. Set to true to enable access or false to restrict it
	SourceAccess *bool `json:"sourceAccess,omitzero"`
	// Generates MP4 video up to 4K ("capped_4k"), m4a audio only ("audioOnly"), or both for offline viewing.
	//
	Mp4Support *DirectUploadVideoMediaMp4Support `json:"mp4Support,omitzero"`
	Summary    *Summary                          `json:"summary,omitzero"`
	// Enable or disable the chapters feature for the media. Set to `true` to enable chapters or `false` to disable.
	//
	Chapters *bool `json:"chapters,omitzero"`
	// Enable or disable named entity extraction. Set to `true` to enable or `false` to disable.
	//
	NamedEntities      *bool                                     `json:"namedEntities,omitzero"`
	Moderation         *DirectUploadVideoMediaModeration         `json:"moderation,omitzero"`
	AccessRestrictions *DirectUploadVideoMediaAccessRestrictions `json:"accessRestrictions,omitzero"`
}

func (p PushMediaSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PushMediaSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PushMediaSettings) GetAccessPolicy() *DirectUploadVideoMediaAccessPolicy {
	if p == nil {
		return nil
	}
	return p.AccessPolicy
}

func (p *PushMediaSettings) GetStartTime() *float64 {
	if p == nil {
		return nil
	}
	return p.StartTime
}

func (p *PushMediaSettings) GetEndTime() *float64 {
	if p == nil {
		return nil
	}
	return p.EndTime
}

func (p *PushMediaSettings) GetInputs() []Input {
	if p == nil {
		return nil
	}
	return p.Inputs
}

func (p *PushMediaSettings) GetMetadata() map[string]string {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *PushMediaSettings) GetDrmConfigurationID() *string {
	if p == nil {
		return nil
	}
	return p.DrmConfigurationID
}

func (p *PushMediaSettings) GetTitle() *string {
	if p == nil {
		return nil
	}
	return p.Title
}

func (p *PushMediaSettings) GetCreatorID() *string {
	if p == nil {
		return nil
	}
	return p.CreatorID
}

func (p *PushMediaSettings) GetSubtitles() *Subtitles {
	if p == nil {
		return nil
	}
	return p.Subtitles
}

func (p *PushMediaSettings) GetOptimizeAudio() *bool {
	if p == nil {
		return nil
	}
	return p.OptimizeAudio
}

func (p *PushMediaSettings) GetMaxResolution() *MaxResolution {
	if p == nil {
		return nil
	}
	return p.MaxResolution
}

func (p *PushMediaSettings) GetMediaQuality() *MediaQuality {
	if p == nil {
		return nil
	}
	return p.MediaQuality
}

func (p *PushMediaSettings) GetSourceAccess() *bool {
	if p == nil {
		return nil
	}
	return p.SourceAccess
}

func (p *PushMediaSettings) GetMp4Support() *DirectUploadVideoMediaMp4Support {
	if p == nil {
		return nil
	}
	return p.Mp4Support
}

func (p *PushMediaSettings) GetSummary() *Summary {
	if p == nil {
		return nil
	}
	return p.Summary
}

func (p *PushMediaSettings) GetChapters() *bool {
	if p == nil {
		return nil
	}
	return p.Chapters
}

func (p *PushMediaSettings) GetNamedEntities() *bool {
	if p == nil {
		return nil
	}
	return p.NamedEntities
}

func (p *PushMediaSettings) GetModeration() *DirectUploadVideoMediaModeration {
	if p == nil {
		return nil
	}
	return p.Moderation
}

func (p *PushMediaSettings) GetAccessRestrictions() *DirectUploadVideoMediaAccessRestrictions {
	if p == nil {
		return nil
	}
	return p.AccessRestrictions
}

// DirectUploadVideoMediaRequest - Request body for direct upload
type DirectUploadVideoMediaRequest struct {
	// Upload media directly from a device using the URL name or enter "*" to allow all.
	CorsOrigin *string `default:"*" json:"corsOrigin"`
	// Configuration settings for uploading and processing media on the FastPix platform.
	// These settings define how the uploaded video is handled, including access control, resolution, DRM, and optional metadata.
	// For a complete explanation of how media uploads and processing work, refer to the
	// <a href="https://docs.fastpix.io/docs/video-on-demand-overview" target="_blank">FastPix Video on Demand Overview</a>.
	//
	PushMediaSettings *PushMediaSettings `json:"pushMediaSettings,omitzero"`
}

func (d DirectUploadVideoMediaRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DirectUploadVideoMediaRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DirectUploadVideoMediaRequest) GetCorsOrigin() *string {
	if d == nil {
		return nil
	}
	return d.CorsOrigin
}

func (d *DirectUploadVideoMediaRequest) GetPushMediaSettings() *PushMediaSettings {
	if d == nil {
		return nil
	}
	return d.PushMediaSettings
}

// DirectUploadVideoMediaResponseBody - Direct upload created successfully
type DirectUploadVideoMediaResponseBody struct {
	// Shows the request status. Returns true for success and false for failure.
	Success bool `json:"success"`
	// Displays the result of the request.
	Data components.DirectUpload `json:"data"`
}

func (d *DirectUploadVideoMediaResponseBody) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DirectUploadVideoMediaResponseBody) GetData() components.DirectUpload {
	if d == nil {
		return components.DirectUpload{}
	}
	return d.Data
}

type DirectUploadVideoMediaResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Direct upload created successfully
	Object *DirectUploadVideoMediaResponseBody
	// See the range of possible <a href="https://docs.fastpix.io/reference/error-codes">error</a> responses and their status codes.
	DefaultError *components.DefaultError
}

func (d DirectUploadVideoMediaResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DirectUploadVideoMediaResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DirectUploadVideoMediaResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DirectUploadVideoMediaResponse) GetObject() *DirectUploadVideoMediaResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}

func (d *DirectUploadVideoMediaResponse) GetDefaultError() *components.DefaultError {
	if d == nil {
		return nil
	}
	return d.DefaultError
}
