/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/models/components"
)

// ListComparisonValuesTimespan - This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
//
// **Accepted formats are:**
//
// array of epoch timestamps for example
// `timespan[]=1498867200&timespan[]=1498953600`
//
// duration string for example
// `timespan[]=24:hours` or `timespan[]=7:days`
type ListComparisonValuesTimespan string

const (
	ListComparisonValuesTimespanSixtyminutes    ListComparisonValuesTimespan = "60:minutes"
	ListComparisonValuesTimespanSixhours        ListComparisonValuesTimespan = "6:hours"
	ListComparisonValuesTimespanTwentyFourhours ListComparisonValuesTimespan = "24:hours"
	ListComparisonValuesTimespanThreedays       ListComparisonValuesTimespan = "3:days"
	ListComparisonValuesTimespanSevendays       ListComparisonValuesTimespan = "7:days"
	ListComparisonValuesTimespanThirtydays      ListComparisonValuesTimespan = "30:days"
)

func (e ListComparisonValuesTimespan) ToPointer() *ListComparisonValuesTimespan {
	return &e
}
func (e *ListComparisonValuesTimespan) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "60:minutes":
		fallthrough
	case "6:hours":
		fallthrough
	case "24:hours":
		fallthrough
	case "3:days":
		fallthrough
	case "7:days":
		fallthrough
	case "30:days":
		*e = ListComparisonValuesTimespan(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListComparisonValuesTimespan: %v", v)
	}
}

// Dimension - The dimension id in which the views are watched.
type Dimension string

const (
	DimensionBrowserName           Dimension = "browser_name"
	DimensionBrowserVersion        Dimension = "browser_version"
	DimensionOsName                Dimension = "os_name"
	DimensionOsVersion             Dimension = "os_version"
	DimensionDeviceName            Dimension = "device_name"
	DimensionDeviceModel           Dimension = "device_model"
	DimensionDeviceType            Dimension = "device_type"
	DimensionDeviceManufacturer    Dimension = "device_manufacturer"
	DimensionPlayerRemotePlayed    Dimension = "player_remote_played"
	DimensionPlayerName            Dimension = "player_name"
	DimensionPlayerVersion         Dimension = "player_version"
	DimensionPlayerSoftwareName    Dimension = "player_software_name"
	DimensionPlayerSoftwareVersion Dimension = "player_software_version"
	DimensionPlayerResolution      Dimension = "player_resolution"
	DimensionFpSDK                 Dimension = "fp_sdk"
	DimensionFpSDKVersion          Dimension = "fp_sdk_version"
	DimensionPlayerAutoplayOn      Dimension = "player_autoplay_on"
	DimensionPlayerPreloadOn       Dimension = "player_preload_on"
	DimensionVideoTitle            Dimension = "video_title"
	DimensionVideoID               Dimension = "video_id"
	DimensionVideoSeries           Dimension = "video_series"
	DimensionFpPlaybackID          Dimension = "fp_playback_id"
	DimensionFpLiveStreamID        Dimension = "fp_live_stream_id"
	DimensionMediaID               Dimension = "media_id"
	DimensionVideoSourceStreamType Dimension = "video_source_stream_type"
	DimensionVideoSourceType       Dimension = "video_source_type"
	DimensionVideoEncodingVariant  Dimension = "video_encoding_variant"
	DimensionExperimentName        Dimension = "experiment_name"
	DimensionSubPropertyID         Dimension = "sub_property_id"
	DimensionDrmType               Dimension = "drm_type"
	DimensionAsnName               Dimension = "asn_name"
	DimensionCdn                   Dimension = "cdn"
	DimensionVideoSourceHostname   Dimension = "video_source_hostname"
	DimensionConnectionType        Dimension = "connection_type"
	DimensionViewSessionID         Dimension = "view_session_id"
	DimensionContinent             Dimension = "continent"
	DimensionCountry               Dimension = "country"
	DimensionRegion                Dimension = "region"
	DimensionViewerID              Dimension = "viewer_id"
	DimensionErrorCode             Dimension = "error_code"
	DimensionExitBeforeVideoStart  Dimension = "exit_before_video_start"
	DimensionViewHasAd             Dimension = "view_has_ad"
	DimensionVideoStartupFailed    Dimension = "video_startup_failed"
	DimensionPageContext           Dimension = "page_context"
	DimensionVideoContentType      Dimension = "video_content_type"
	DimensionPlaybackFailed        Dimension = "playback_failed"
	DimensionCustom1               Dimension = "custom_1"
	DimensionCustom2               Dimension = "custom_2"
	DimensionCustom3               Dimension = "custom_3"
	DimensionCustom4               Dimension = "custom_4"
	DimensionCustom5               Dimension = "custom_5"
	DimensionCustom6               Dimension = "custom_6"
	DimensionCustom7               Dimension = "custom_7"
	DimensionCustom8               Dimension = "custom_8"
	DimensionCustom9               Dimension = "custom_9"
	DimensionCustom10              Dimension = "custom_10"
)

func (e Dimension) ToPointer() *Dimension {
	return &e
}
func (e *Dimension) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "browser_name":
		fallthrough
	case "browser_version":
		fallthrough
	case "os_name":
		fallthrough
	case "os_version":
		fallthrough
	case "device_name":
		fallthrough
	case "device_model":
		fallthrough
	case "device_type":
		fallthrough
	case "device_manufacturer":
		fallthrough
	case "player_remote_played":
		fallthrough
	case "player_name":
		fallthrough
	case "player_version":
		fallthrough
	case "player_software_name":
		fallthrough
	case "player_software_version":
		fallthrough
	case "player_resolution":
		fallthrough
	case "fp_sdk":
		fallthrough
	case "fp_sdk_version":
		fallthrough
	case "player_autoplay_on":
		fallthrough
	case "player_preload_on":
		fallthrough
	case "video_title":
		fallthrough
	case "video_id":
		fallthrough
	case "video_series":
		fallthrough
	case "fp_playback_id":
		fallthrough
	case "fp_live_stream_id":
		fallthrough
	case "media_id":
		fallthrough
	case "video_source_stream_type":
		fallthrough
	case "video_source_type":
		fallthrough
	case "video_encoding_variant":
		fallthrough
	case "experiment_name":
		fallthrough
	case "sub_property_id":
		fallthrough
	case "drm_type":
		fallthrough
	case "asn_name":
		fallthrough
	case "cdn":
		fallthrough
	case "video_source_hostname":
		fallthrough
	case "connection_type":
		fallthrough
	case "view_session_id":
		fallthrough
	case "continent":
		fallthrough
	case "country":
		fallthrough
	case "region":
		fallthrough
	case "viewer_id":
		fallthrough
	case "error_code":
		fallthrough
	case "exit_before_video_start":
		fallthrough
	case "view_has_ad":
		fallthrough
	case "video_startup_failed":
		fallthrough
	case "page_context":
		fallthrough
	case "video_content_type":
		fallthrough
	case "playback_failed":
		fallthrough
	case "custom_1":
		fallthrough
	case "custom_2":
		fallthrough
	case "custom_3":
		fallthrough
	case "custom_4":
		fallthrough
	case "custom_5":
		fallthrough
	case "custom_6":
		fallthrough
	case "custom_7":
		fallthrough
	case "custom_8":
		fallthrough
	case "custom_9":
		fallthrough
	case "custom_10":
		*e = Dimension(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Dimension: %v", v)
	}
}

type ListComparisonValuesRequest struct {
	// This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
	//
	// **Accepted formats are:**
	//
	// array of epoch timestamps for example
	// `timespan[]=1498867200&timespan[]=1498953600`
	//
	// duration string for example
	// `timespan[]=24:hours` or `timespan[]=7:days`
	//
	Timespan *ListComparisonValuesTimespan `queryParam:"style=form,explode=true,name=timespan[]"`
	// Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass "!" before the filter value. The list of filters can be obtained from list of dimensions endpoint.
	// Example Values : [ browser_name:Chrome , os_name:macOS , !device_name:Galaxy ]
	//
	Filterby *string `queryParam:"style=form,explode=true,name=filterby[]"`
	// The dimension id in which the views are watched.
	//
	Dimension *Dimension `queryParam:"style=form,explode=true,name=dimension"`
	// The value for the selected dimension.
	// For example:
	//  If `dimension` is `browser_name`, the value could be  `Chrome` `,` `Firefox` `etc` .
	//  If `dimension` is `os_name`, the value could be `macOS` `,` `Windows` `etc` .
	//
	Value *string `queryParam:"style=form,explode=true,name=value"`
}

func (l *ListComparisonValuesRequest) GetTimespan() *ListComparisonValuesTimespan {
	if l == nil {
		return nil
	}
	return l.Timespan
}

func (l *ListComparisonValuesRequest) GetFilterby() *string {
	if l == nil {
		return nil
	}
	return l.Filterby
}

func (l *ListComparisonValuesRequest) GetDimension() *Dimension {
	if l == nil {
		return nil
	}
	return l.Dimension
}

func (l *ListComparisonValuesRequest) GetValue() *string {
	if l == nil {
		return nil
	}
	return l.Value
}

// ListComparisonValuesResponseBody - Get filter/ dimension value details by dimension name.
type ListComparisonValuesResponseBody struct {
	// Shows the request status. Returns true for success and false for failure.
	Success *bool `json:"success,omitzero"`
	// Displays the result of the request.
	//
	Data []components.MetricsComparisonDetails `json:"data,omitzero"`
	// The timespan from and to details displayed in the form of unix epoch timestamps.
	//
	Timespan []int64 `json:"timespan,omitzero"`
}

func (l ListComparisonValuesResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListComparisonValuesResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListComparisonValuesResponseBody) GetSuccess() *bool {
	if l == nil {
		return nil
	}
	return l.Success
}

func (l *ListComparisonValuesResponseBody) GetData() []components.MetricsComparisonDetails {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListComparisonValuesResponseBody) GetTimespan() []int64 {
	if l == nil {
		return nil
	}
	return l.Timespan
}

type ListComparisonValuesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Get filter/ dimension value details by dimension name.
	Object *ListComparisonValuesResponseBody
	// See the range of possible <a href="https://docs.fastpix.io/reference/error-codes">error</a> responses and their status codes.
	DefaultError *components.DefaultError
}

func (l ListComparisonValuesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListComparisonValuesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListComparisonValuesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListComparisonValuesResponse) GetObject() *ListComparisonValuesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListComparisonValuesResponse) GetDefaultError() *components.DefaultError {
	if l == nil {
		return nil
	}
	return l.DefaultError
}
