

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/fastpix/fastpix-go/internal/utils"
	"github.com/fastpix/fastpix-go/models/components"
	"github.com/fastpix/fastpix-go/optionalnullable"
)

// ListVideoViewsTimespan - This parameter specifies the time span between which the video views list should be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
type ListVideoViewsTimespan string

const (
	ListVideoViewsTimespanSixtyminutes    ListVideoViewsTimespan = "60:minutes"
	ListVideoViewsTimespanSixhours        ListVideoViewsTimespan = "6:hours"
	ListVideoViewsTimespanTwentyFourhours ListVideoViewsTimespan = "24:hours"
	ListVideoViewsTimespanThreedays       ListVideoViewsTimespan = "3:days"
	ListVideoViewsTimespanSevendays       ListVideoViewsTimespan = "7:days"
	ListVideoViewsTimespanThirtydays      ListVideoViewsTimespan = "30:days"
)

func (e ListVideoViewsTimespan) ToPointer() *ListVideoViewsTimespan {
	return &e
}
func (e *ListVideoViewsTimespan) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "60:minutes":
		fallthrough
	case "6:hours":
		fallthrough
	case "24:hours":
		fallthrough
	case "3:days":
		fallthrough
	case "7:days":
		fallthrough
	case "30:days":
		*e = ListVideoViewsTimespan(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListVideoViewsTimespan: %v", v)
	}
}

type ErrorCodeType string

const (
	ErrorCodeTypeStr     ErrorCodeType = "str"
	ErrorCodeTypeInteger ErrorCodeType = "integer"
)

// ErrorCode - Pass the error code to filter the list of views. The possible values of error code can be fetched from list of errors end point.
type ErrorCode struct {
	Str     *string `queryParam:"inline,name=errorCode"`
	Integer *int64  `queryParam:"inline,name=errorCode"`

	Type ErrorCodeType
}

func CreateErrorCodeStr(str string) ErrorCode {
	typ := ErrorCodeTypeStr

	return ErrorCode{
		Str:  &str,
		Type: typ,
	}
}

func CreateErrorCodeInteger(integer int64) ErrorCode {
	typ := ErrorCodeTypeInteger

	return ErrorCode{
		Integer: &integer,
		Type:    typ,
	}
}

func (u *ErrorCode) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = ErrorCodeTypeStr
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = ErrorCodeTypeInteger
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ErrorCode", string(data))
}

func (u ErrorCode) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	return nil, errors.New("could not marshal union type ErrorCode: all fields are null")
}

type ListVideoViewsRequest struct {
	// This parameter specifies the time span between which the video views list should be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
	//
	Timespan ListVideoViewsTimespan `queryParam:"style=form,explode=true,name=timespan[]"`
	// Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass '!' before the filter value. The list of filters can be obtained from list of dimensions endpoint.
	// Example Values : [ browser_name:Chrome , os_name:macOS , device_name:Galaxy ]
	//
	Filterby *string `queryParam:"style=form,explode=true,name=filterby[]"`
	// Pass the limit to display only the rows specified by the value.
	//
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Pass the offset value to indicate the page number.
	//
	Offset *int64 `default:"1" queryParam:"style=form,explode=true,name=offset"`
	// Pass the viewer_id to filter the list of views. This value can be manually set during integration or generated by FastPix. When set manually it can be a string of aplha numeric values of any length.
	//
	ViewerID *string `queryParam:"style=form,explode=true,name=viewerId"`
	// Pass the error code to filter the list of views. The possible values of error code can be fetched from list of errors end point.
	//
	ErrorCode optionalnullable.OptionalNullable[ErrorCode] `queryParam:"style=form,explode=true,name=errorCode"`
	// Pass this value to sort the view list by.
	//
	OrderBy *string `default:"view_end" queryParam:"style=form,explode=true,name=orderBy"`
	// The order direction to sort the view list by.
	//
	SortOrder *string `default:"asc" queryParam:"style=form,explode=true,name=sortOrder"`
}

func (l ListVideoViewsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListVideoViewsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"timespan[]"}); err != nil {
		return err
	}
	return nil
}

func (l *ListVideoViewsRequest) GetTimespan() ListVideoViewsTimespan {
	if l == nil {
		return ListVideoViewsTimespan("")
	}
	return l.Timespan
}

func (l *ListVideoViewsRequest) GetFilterby() *string {
	if l == nil {
		return nil
	}
	return l.Filterby
}

func (l *ListVideoViewsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListVideoViewsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListVideoViewsRequest) GetViewerID() *string {
	if l == nil {
		return nil
	}
	return l.ViewerID
}

func (l *ListVideoViewsRequest) GetErrorCode() optionalnullable.OptionalNullable[ErrorCode] {
	if l == nil {
		return nil
	}
	return l.ErrorCode
}

func (l *ListVideoViewsRequest) GetOrderBy() *string {
	if l == nil {
		return nil
	}
	return l.OrderBy
}

func (l *ListVideoViewsRequest) GetSortOrder() *string {
	if l == nil {
		return nil
	}
	return l.SortOrder
}

// ListVideoViewsResponseBody - Get the list of Views
type ListVideoViewsResponseBody struct {
	// It demonstrates whether the request is successful or not.
	Success *bool `json:"success,omitempty"`
	// Displays the result of the request.
	Data []components.ViewsList `json:"data,omitempty"`
	// Pagination organizes content into pages for better readability and navigation.
	Pagination *components.DataPagination `json:"pagination,omitempty"`
	// The timeframe from and to details displayed in the form of unix epoch timestamps.
	//
	Timespan []int64 `json:"timespan,omitempty"`
}

func (l *ListVideoViewsResponseBody) GetSuccess() *bool {
	if l == nil {
		return nil
	}
	return l.Success
}

func (l *ListVideoViewsResponseBody) GetData() []components.ViewsList {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListVideoViewsResponseBody) GetPagination() *components.DataPagination {
	if l == nil {
		return nil
	}
	return l.Pagination
}

func (l *ListVideoViewsResponseBody) GetTimespan() []int64 {
	if l == nil {
		return nil
	}
	return l.Timespan
}

type ListVideoViewsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Get the list of Views
	Object *ListVideoViewsResponseBody
}

func (l *ListVideoViewsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListVideoViewsResponse) GetObject() *ListVideoViewsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
