/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/models/components"
)

// UpdateLiveStreamUserAgentRestrictionsDefaultPolicy - The default behavior when a user-agent is not listed in `allow` or `deny`.
type UpdateLiveStreamUserAgentRestrictionsDefaultPolicy string

const (
	UpdateLiveStreamUserAgentRestrictionsDefaultPolicyAllow UpdateLiveStreamUserAgentRestrictionsDefaultPolicy = "allow"
	UpdateLiveStreamUserAgentRestrictionsDefaultPolicyDeny  UpdateLiveStreamUserAgentRestrictionsDefaultPolicy = "deny"
)

func (e UpdateLiveStreamUserAgentRestrictionsDefaultPolicy) ToPointer() *UpdateLiveStreamUserAgentRestrictionsDefaultPolicy {
	return &e
}
func (e *UpdateLiveStreamUserAgentRestrictionsDefaultPolicy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "allow":
		fallthrough
	case "deny":
		*e = UpdateLiveStreamUserAgentRestrictionsDefaultPolicy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateLiveStreamUserAgentRestrictionsDefaultPolicy: %v", v)
	}
}

type UpdateLiveStreamUserAgentRestrictionsRequestBody struct {
	// The default behavior when a user-agent is not listed in `allow` or `deny`.
	DefaultPolicy *UpdateLiveStreamUserAgentRestrictionsDefaultPolicy `default:"allow" json:"defaultPolicy"`
	// List of user-agent substrings explicitly allowed.
	Allow []string `json:"allow,omitzero"`
	// List of user-agent substrings explicitly denied.
	Deny []string `json:"deny,omitzero"`
}

func (u UpdateLiveStreamUserAgentRestrictionsRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateLiveStreamUserAgentRestrictionsRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateLiveStreamUserAgentRestrictionsRequestBody) GetDefaultPolicy() *UpdateLiveStreamUserAgentRestrictionsDefaultPolicy {
	if u == nil {
		return nil
	}
	return u.DefaultPolicy
}

func (u *UpdateLiveStreamUserAgentRestrictionsRequestBody) GetAllow() []string {
	if u == nil {
		return nil
	}
	return u.Allow
}

func (u *UpdateLiveStreamUserAgentRestrictionsRequestBody) GetDeny() []string {
	if u == nil {
		return nil
	}
	return u.Deny
}

type UpdateLiveStreamUserAgentRestrictionsRequest struct {
	StreamID   string                                           `pathParam:"style=simple,explode=false,name=streamId"`
	PlaybackID string                                           `pathParam:"style=simple,explode=false,name=playbackId"`
	Body       UpdateLiveStreamUserAgentRestrictionsRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateLiveStreamUserAgentRestrictionsRequest) GetStreamID() string {
	if u == nil {
		return ""
	}
	return u.StreamID
}

func (u *UpdateLiveStreamUserAgentRestrictionsRequest) GetPlaybackID() string {
	if u == nil {
		return ""
	}
	return u.PlaybackID
}

func (u *UpdateLiveStreamUserAgentRestrictionsRequest) GetBody() UpdateLiveStreamUserAgentRestrictionsRequestBody {
	if u == nil {
		return UpdateLiveStreamUserAgentRestrictionsRequestBody{}
	}
	return u.Body
}

type UpdateLiveStreamUserAgentRestrictionsData struct {
	// Specifies the default behavior for user agents not listed in the allow or deny lists.
	DefaultPolicy *string `json:"defaultPolicy,omitzero"`
	// List of user-agent substrings explicitly allowed.
	Allow []string `json:"allow,omitzero"`
	// List of user-agent substrings explicitly denied.
	Deny []string `json:"deny,omitzero"`
}

func (u UpdateLiveStreamUserAgentRestrictionsData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateLiveStreamUserAgentRestrictionsData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateLiveStreamUserAgentRestrictionsData) GetDefaultPolicy() *string {
	if u == nil {
		return nil
	}
	return u.DefaultPolicy
}

func (u *UpdateLiveStreamUserAgentRestrictionsData) GetAllow() []string {
	if u == nil {
		return nil
	}
	return u.Allow
}

func (u *UpdateLiveStreamUserAgentRestrictionsData) GetDeny() []string {
	if u == nil {
		return nil
	}
	return u.Deny
}

// UpdateLiveStreamUserAgentRestrictionsResponseBody - Successfully updated user-agent restrictions
type UpdateLiveStreamUserAgentRestrictionsResponseBody struct {
	// Shows the request status. Returns true for success and false for failure.
	Success *bool                                      `json:"success,omitzero"`
	Data    *UpdateLiveStreamUserAgentRestrictionsData `json:"data,omitzero"`
}

func (u UpdateLiveStreamUserAgentRestrictionsResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateLiveStreamUserAgentRestrictionsResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateLiveStreamUserAgentRestrictionsResponseBody) GetSuccess() *bool {
	if u == nil {
		return nil
	}
	return u.Success
}

func (u *UpdateLiveStreamUserAgentRestrictionsResponseBody) GetData() *UpdateLiveStreamUserAgentRestrictionsData {
	if u == nil {
		return nil
	}
	return u.Data
}

type UpdateLiveStreamUserAgentRestrictionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully updated user-agent restrictions
	Object *UpdateLiveStreamUserAgentRestrictionsResponseBody
	// See the range of possible <a href="https://fastpix.com/docs/error-codes/error-codes">error</a> responses and their status codes.
	DefaultError *components.DefaultError
}

func (u UpdateLiveStreamUserAgentRestrictionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateLiveStreamUserAgentRestrictionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateLiveStreamUserAgentRestrictionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateLiveStreamUserAgentRestrictionsResponse) GetObject() *UpdateLiveStreamUserAgentRestrictionsResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UpdateLiveStreamUserAgentRestrictionsResponse) GetDefaultError() *components.DefaultError {
	if u == nil {
		return nil
	}
	return u.DefaultError
}
