/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package operations

import (
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/models/components"
)

type UpdateAPlaylistRequest struct {
	// The unique id of the playlist you want to retrieve.
	PlaylistID string                           `pathParam:"style=simple,explode=false,name=playlistId"`
	Body       components.UpdatePlaylistRequest `request:"mediaType=application/json"`
}

func (u *UpdateAPlaylistRequest) GetPlaylistID() string {
	if u == nil {
		return ""
	}
	return u.PlaylistID
}

func (u *UpdateAPlaylistRequest) GetBody() components.UpdatePlaylistRequest {
	if u == nil {
		return components.UpdatePlaylistRequest{}
	}
	return u.Body
}

type UpdateAPlaylistResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Playlist updated successfully
	PlaylistCreatedResponse *components.PlaylistCreatedResponse
	// See the range of possible <a href="https://docs.fastpix.io/reference/error-codes">error</a> responses and their status codes.
	DefaultError *components.DefaultError
}

func (u UpdateAPlaylistResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAPlaylistResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAPlaylistResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAPlaylistResponse) GetPlaylistCreatedResponse() *components.PlaylistCreatedResponse {
	if u == nil {
		return nil
	}
	return u.PlaylistCreatedResponse
}

func (u *UpdateAPlaylistResponse) GetDefaultError() *components.DefaultError {
	if u == nil {
		return nil
	}
	return u.DefaultError
}
