/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/models/components"
)

// UpdateLiveStreamDomainRestrictionsDefaultPolicy - Specify the fallback behavior for domains that are not listed in the `allow` or `deny` lists.
type UpdateLiveStreamDomainRestrictionsDefaultPolicy string

const (
	UpdateLiveStreamDomainRestrictionsDefaultPolicyAllow UpdateLiveStreamDomainRestrictionsDefaultPolicy = "allow"
	UpdateLiveStreamDomainRestrictionsDefaultPolicyDeny  UpdateLiveStreamDomainRestrictionsDefaultPolicy = "deny"
)

func (e UpdateLiveStreamDomainRestrictionsDefaultPolicy) ToPointer() *UpdateLiveStreamDomainRestrictionsDefaultPolicy {
	return &e
}
func (e *UpdateLiveStreamDomainRestrictionsDefaultPolicy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "allow":
		fallthrough
	case "deny":
		*e = UpdateLiveStreamDomainRestrictionsDefaultPolicy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateLiveStreamDomainRestrictionsDefaultPolicy: %v", v)
	}
}

type UpdateLiveStreamDomainRestrictionsRequestBody struct {
	// Specify the fallback behavior for domains that are not listed in the `allow` or `deny` lists.
	DefaultPolicy *UpdateLiveStreamDomainRestrictionsDefaultPolicy `default:"allow" json:"defaultPolicy"`
	// List of domains explicitly allowed to play the media.
	Allow []string `json:"allow,omitzero"`
	// List of domains explicitly denied from accessing the media.
	Deny []string `json:"deny,omitzero"`
}

func (u UpdateLiveStreamDomainRestrictionsRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateLiveStreamDomainRestrictionsRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateLiveStreamDomainRestrictionsRequestBody) GetDefaultPolicy() *UpdateLiveStreamDomainRestrictionsDefaultPolicy {
	if u == nil {
		return nil
	}
	return u.DefaultPolicy
}

func (u *UpdateLiveStreamDomainRestrictionsRequestBody) GetAllow() []string {
	if u == nil {
		return nil
	}
	return u.Allow
}

func (u *UpdateLiveStreamDomainRestrictionsRequestBody) GetDeny() []string {
	if u == nil {
		return nil
	}
	return u.Deny
}

type UpdateLiveStreamDomainRestrictionsRequest struct {
	StreamID   string                                        `pathParam:"style=simple,explode=false,name=streamId"`
	PlaybackID string                                        `pathParam:"style=simple,explode=false,name=playbackId"`
	Body       UpdateLiveStreamDomainRestrictionsRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateLiveStreamDomainRestrictionsRequest) GetStreamID() string {
	if u == nil {
		return ""
	}
	return u.StreamID
}

func (u *UpdateLiveStreamDomainRestrictionsRequest) GetPlaybackID() string {
	if u == nil {
		return ""
	}
	return u.PlaybackID
}

func (u *UpdateLiveStreamDomainRestrictionsRequest) GetBody() UpdateLiveStreamDomainRestrictionsRequestBody {
	if u == nil {
		return UpdateLiveStreamDomainRestrictionsRequestBody{}
	}
	return u.Body
}

type UpdateLiveStreamDomainRestrictionsData struct {
	// Specify the fallback behavior for domains that are not listed in the allow or deny lists.
	DefaultPolicy *string `json:"defaultPolicy,omitzero"`
	// List of domains explicitly allowed to play the media.
	Allow []string `json:"allow,omitzero"`
	// List of domains explicitly denied from accessing the media.
	Deny []string `json:"deny,omitzero"`
}

func (u UpdateLiveStreamDomainRestrictionsData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateLiveStreamDomainRestrictionsData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateLiveStreamDomainRestrictionsData) GetDefaultPolicy() *string {
	if u == nil {
		return nil
	}
	return u.DefaultPolicy
}

func (u *UpdateLiveStreamDomainRestrictionsData) GetAllow() []string {
	if u == nil {
		return nil
	}
	return u.Allow
}

func (u *UpdateLiveStreamDomainRestrictionsData) GetDeny() []string {
	if u == nil {
		return nil
	}
	return u.Deny
}

// UpdateLiveStreamDomainRestrictionsResponseBody - Successfully updated domain restrictions
type UpdateLiveStreamDomainRestrictionsResponseBody struct {
	// Shows the request status. Returns true for success and false for failure.
	Success *bool                                   `json:"success,omitzero"`
	Data    *UpdateLiveStreamDomainRestrictionsData `json:"data,omitzero"`
}

func (u UpdateLiveStreamDomainRestrictionsResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateLiveStreamDomainRestrictionsResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateLiveStreamDomainRestrictionsResponseBody) GetSuccess() *bool {
	if u == nil {
		return nil
	}
	return u.Success
}

func (u *UpdateLiveStreamDomainRestrictionsResponseBody) GetData() *UpdateLiveStreamDomainRestrictionsData {
	if u == nil {
		return nil
	}
	return u.Data
}

type UpdateLiveStreamDomainRestrictionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully updated domain restrictions
	Object *UpdateLiveStreamDomainRestrictionsResponseBody
	// See the range of possible <a href="https://fastpix.com/docs/error-codes/error-codes">error</a> responses and their status codes.
	DefaultError *components.DefaultError
}

func (u UpdateLiveStreamDomainRestrictionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateLiveStreamDomainRestrictionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateLiveStreamDomainRestrictionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateLiveStreamDomainRestrictionsResponse) GetObject() *UpdateLiveStreamDomainRestrictionsResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UpdateLiveStreamDomainRestrictionsResponse) GetDefaultError() *components.DefaultError {
	if u == nil {
		return nil
	}
	return u.DefaultError
}
