/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
)

// AccessRestrictions - Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents.
type AccessRestrictions struct {
	// Restrictions based on the originating domain of a request
	Domains *DomainRestrictions `json:"domains,omitzero"`
	// Restrictions based on the user agent
	UserAgents *UserAgentRestrictions `json:"userAgents,omitzero"`
}

func (a AccessRestrictions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccessRestrictions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccessRestrictions) GetDomains() *DomainRestrictions {
	if a == nil {
		return nil
	}
	return a.Domains
}

func (a *AccessRestrictions) GetUserAgents() *UserAgentRestrictions {
	if a == nil {
		return nil
	}
	return a.UserAgents
}
