/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

type BrowserNameDimensiondetails struct {
	// The specific metric value calculated based on the applied filters.
	Value *string `json:"value,omitzero"`
	// The count of unique viewers who interacted with the content.
	UniqueCount *int64 `json:"uniqueCount,omitzero"`
	// The count of viewers.
	Count *int64 `json:"count,omitzero"`
}

func (b *BrowserNameDimensiondetails) GetValue() *string {
	if b == nil {
		return nil
	}
	return b.Value
}

func (b *BrowserNameDimensiondetails) GetUniqueCount() *int64 {
	if b == nil {
		return nil
	}
	return b.UniqueCount
}

func (b *BrowserNameDimensiondetails) GetCount() *int64 {
	if b == nil {
		return nil
	}
	return b.Count
}
