/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

type ChaptersResponse struct {
	MediaID           *string `json:"mediaId,omitzero"`
	IsChaptersEnabled *bool   `json:"isChaptersEnabled,omitzero"`
}

func (c *ChaptersResponse) GetMediaID() *string {
	if c == nil {
		return nil
	}
	return c.MediaID
}

func (c *ChaptersResponse) GetIsChaptersEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.IsChaptersEnabled
}
