/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"encoding/json"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/utils"
)

// CreatePlaylistRequestSmartType - For a smart playlist metadata is required.
type CreatePlaylistRequestSmartType string

const (
	CreatePlaylistRequestSmartTypeSmart CreatePlaylistRequestSmartType = "smart"
)

func (e CreatePlaylistRequestSmartType) ToPointer() *CreatePlaylistRequestSmartType {
	return &e
}
func (e *CreatePlaylistRequestSmartType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "smart":
		*e = CreatePlaylistRequestSmartType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreatePlaylistRequestSmartType: %v", v)
	}
}

// Metadata - Required when the playlist type is `smart`. Media created between `startDate` and `endDate` of `createdDate` is added. Optionally, you can include media based on `updatedDate`.
type Metadata struct {
	// Date range with start and end dates.
	CreatedDate *DateRange `json:"createdDate,omitzero"`
	// Date range with start and end dates.
	UpdatedDate *DateRange `json:"updatedDate,omitzero"`
}

func (m Metadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Metadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *Metadata) GetCreatedDate() *DateRange {
	if m == nil {
		return nil
	}
	return m.CreatedDate
}

func (m *Metadata) GetUpdatedDate() *DateRange {
	if m == nil {
		return nil
	}
	return m.UpdatedDate
}

type CreatePlaylistRequestSmart struct {
	// Name of the playlist.
	Name string `json:"name"`
	// Unique string value assigned by user to the playlist.
	ReferenceID string `json:"referenceId"`
	// For a smart playlist metadata is required.
	Type CreatePlaylistRequestSmartType `json:"type"`
	// Description for a playlist (Optional).
	Description *string `json:"description,omitzero"`
	// Determines the insertion order of media into playlist.
	PlayOrder PlaylistOrder `json:"playOrder"`
	// Optional parameter to limit no. of media in a playlist.
	Limit *int64 `default:"1000" json:"limit"`
	// Required when the playlist type is `smart`. Media created between `startDate` and `endDate` of `createdDate` is added. Optionally, you can include media based on `updatedDate`.
	Metadata Metadata `json:"metadata"`
}

func (c CreatePlaylistRequestSmart) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePlaylistRequestSmart) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePlaylistRequestSmart) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreatePlaylistRequestSmart) GetReferenceID() string {
	if c == nil {
		return ""
	}
	return c.ReferenceID
}

func (c *CreatePlaylistRequestSmart) GetType() CreatePlaylistRequestSmartType {
	if c == nil {
		return CreatePlaylistRequestSmartType("")
	}
	return c.Type
}

func (c *CreatePlaylistRequestSmart) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreatePlaylistRequestSmart) GetPlayOrder() PlaylistOrder {
	if c == nil {
		return PlaylistOrder("")
	}
	return c.PlayOrder
}

func (c *CreatePlaylistRequestSmart) GetLimit() *int64 {
	if c == nil {
		return nil
	}
	return c.Limit
}

func (c *CreatePlaylistRequestSmart) GetMetadata() Metadata {
	if c == nil {
		return Metadata{}
	}
	return c.Metadata
}
