/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
)

// DateRange - Date range with start and end dates.
type DateRange struct {
	StartDate *string `json:"startDate,omitzero"`
	EndDate   *string `json:"endDate,omitzero"`
}

func (d DateRange) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DateRange) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DateRange) GetStartDate() *string {
	if d == nil {
		return nil
	}
	return d.StartDate
}

func (d *DateRange) GetEndDate() *string {
	if d == nil {
		return nil
	}
	return d.EndDate
}
