/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

type DeleteSigningKeyResponse struct {
	// Shows the request status. Returns true for success and false for failure.
	Success *bool `json:"success,omitzero"`
}

func (d *DeleteSigningKeyResponse) GetSuccess() *bool {
	if d == nil {
		return nil
	}
	return d.Success
}
