/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
)

// DirectUploadResponseMediaQuality - The quality tier applied to the media.
type DirectUploadResponseMediaQuality string

const (
	DirectUploadResponseMediaQualityStandard DirectUploadResponseMediaQuality = "standard"
	DirectUploadResponseMediaQualityPro      DirectUploadResponseMediaQuality = "pro"
	DirectUploadResponseMediaQualityPremium  DirectUploadResponseMediaQuality = "premium"
)

func (e DirectUploadResponseMediaQuality) ToPointer() *DirectUploadResponseMediaQuality {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DirectUploadResponseMediaQuality) IsExact() bool {
	if e != nil {
		switch *e {
		case "standard", "pro", "premium":
			return true
		}
	}
	return false
}

type DirectUploadResponse struct {
	PlaybackIds []PlaybackID `json:"playbackIds,omitzero"`
	// You can search for videos with specific key value pairs using metadata, when you tag a video in "key" : "value" pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
	//
	Metadata map[string]string `json:"metadata,omitzero"`
	// The quality tier applied to the media.
	MediaQuality *DirectUploadResponseMediaQuality `json:"mediaQuality,omitzero"`
	// The sourceAccess parameter determines whether the original media file is accessible. Set to true to enable access or false to restrict it.
	//
	SourceAccess *bool `json:"sourceAccess,omitzero"`
	// Enhance the quality and volume of the audio track. This is available for pre-recorded content only.
	//
	OptimizeAudio *bool `json:"optimizeAudio,omitzero"`
}

func (d DirectUploadResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DirectUploadResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DirectUploadResponse) GetPlaybackIds() []PlaybackID {
	if d == nil {
		return nil
	}
	return d.PlaybackIds
}

func (d *DirectUploadResponse) GetMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DirectUploadResponse) GetMediaQuality() *DirectUploadResponseMediaQuality {
	if d == nil {
		return nil
	}
	return d.MediaQuality
}

func (d *DirectUploadResponse) GetSourceAccess() *bool {
	if d == nil {
		return nil
	}
	return d.SourceAccess
}

func (d *DirectUploadResponse) GetOptimizeAudio() *bool {
	if d == nil {
		return nil
	}
	return d.OptimizeAudio
}
