/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"encoding/json"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/utils"
)

// DirectUploadStatus - Determines the media's status, which can be one of the possible values.
type DirectUploadStatus string

const (
	DirectUploadStatusWaiting DirectUploadStatus = "waiting"
)

func (e DirectUploadStatus) ToPointer() *DirectUploadStatus {
	return &e
}
func (e *DirectUploadStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "waiting":
		*e = DirectUploadStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DirectUploadStatus: %v", v)
	}
}

// DirectUpload - Displays the result of the request.
type DirectUpload struct {
	// The unique identifier assigned to the media when created. The value must be a valid UUID.
	UploadID *string `json:"uploadId,omitzero"`
	// Indicates if the upload was a trial.
	Trial *bool `json:"trial,omitzero"`
	// Determines the media's status, which can be one of the possible values.
	Status *DirectUploadStatus `json:"status,omitzero"`
	// The url hosts the media file for FastPix, which needs to be download to use further.  It supports formats like MP3, MP4, MOV, MKV, or TS, and includes text tracks for subtitles/CC (SRT file/VTT file). While FastPix can handle various audio and video formats and codecs, using standard inputs can help with optimal processing speed.
	URL *string `json:"url,omitzero"`
	// The duration set for the validity of the upload URL. If the upload isn't completed within this timespan, it's marked as timed out.
	//
	Timeout *float64 `default:"14400" json:"timeout"`
	// Upload media directly from a device using the url name or enter "*" to allow all.
	CorsOrigin        *string               `json:"corsOrigin,omitzero"`
	PushMediaSettings *DirectUploadResponse `json:"pushMediaSettings,omitzero"`
}

func (d DirectUpload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DirectUpload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DirectUpload) GetUploadID() *string {
	if d == nil {
		return nil
	}
	return d.UploadID
}

func (d *DirectUpload) GetTrial() *bool {
	if d == nil {
		return nil
	}
	return d.Trial
}

func (d *DirectUpload) GetStatus() *DirectUploadStatus {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DirectUpload) GetURL() *string {
	if d == nil {
		return nil
	}
	return d.URL
}

func (d *DirectUpload) GetTimeout() *float64 {
	if d == nil {
		return nil
	}
	return d.Timeout
}

func (d *DirectUpload) GetCorsOrigin() *string {
	if d == nil {
		return nil
	}
	return d.CorsOrigin
}

func (d *DirectUpload) GetPushMediaSettings() *DirectUploadResponse {
	if d == nil {
		return nil
	}
	return d.PushMediaSettings
}
