/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"errors"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/optionalnullable"
)

type ErrorDetailsPercentageType string

const (
	ErrorDetailsPercentageTypeInteger ErrorDetailsPercentageType = "integer"
	ErrorDetailsPercentageTypeNumber  ErrorDetailsPercentageType = "number"
)

// ErrorDetailsPercentage - views affected by the specific errors.
type ErrorDetailsPercentage struct {
	Integer *int64   `queryParam:"inline" union:"member"`
	Number  *float64 `queryParam:"inline" union:"member"`

	Type ErrorDetailsPercentageType
}

func CreateErrorDetailsPercentageInteger(integer int64) ErrorDetailsPercentage {
	typ := ErrorDetailsPercentageTypeInteger

	return ErrorDetailsPercentage{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateErrorDetailsPercentageNumber(number float64) ErrorDetailsPercentage {
	typ := ErrorDetailsPercentageTypeNumber

	return ErrorDetailsPercentage{
		Number: &number,
		Type:   typ,
	}
}

func (u *ErrorDetailsPercentage) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ErrorDetailsPercentageTypeInteger,
			Value: &integer,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ErrorDetailsPercentageTypeNumber,
			Value: &number,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ErrorDetailsPercentage", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ErrorDetailsPercentage", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ErrorDetailsPercentageType)
	switch best.Type {
	case ErrorDetailsPercentageTypeInteger:
		u.Integer = best.Value.(*int64)
		return nil
	case ErrorDetailsPercentageTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ErrorDetailsPercentage", string(data))
}

func (u ErrorDetailsPercentage) MarshalJSON() ([]byte, error) {
	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type ErrorDetailsPercentage: all fields are null")
}

type ErrorDetails struct {
	// views affected by the specific errors.
	Percentage optionalnullable.OptionalNullable[ErrorDetailsPercentage] `json:"percentage,omitzero"`
	// Information about the specific error.
	Notes optionalnullable.OptionalNullable[string] `json:"notes,omitzero"`
	// error message or description.
	Message optionalnullable.OptionalNullable[string] `json:"message,omitzero"`
	// The timestamp of when the error was last observed.
	LastSeen optionalnullable.OptionalNullable[string] `json:"lastSeen,omitzero"`
	// Unique identifier for the error instance.
	ID optionalnullable.OptionalNullable[string] `json:"id,omitzero"`
	// A brief description of the error.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// Number of occurrences of the specific error.
	Count optionalnullable.OptionalNullable[int64] `json:"count,omitzero"`
	// Error code associated with the specific error.
	Code optionalnullable.OptionalNullable[string] `json:"code,omitzero"`
}

func (e *ErrorDetails) GetPercentage() optionalnullable.OptionalNullable[ErrorDetailsPercentage] {
	if e == nil {
		return nil
	}
	return e.Percentage
}

func (e *ErrorDetails) GetNotes() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Notes
}

func (e *ErrorDetails) GetMessage() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *ErrorDetails) GetLastSeen() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.LastSeen
}

func (e *ErrorDetails) GetID() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ErrorDetails) GetDescription() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *ErrorDetails) GetCount() optionalnullable.OptionalNullable[int64] {
	if e == nil {
		return nil
	}
	return e.Count
}

func (e *ErrorDetails) GetCode() optionalnullable.OptionalNullable[string] {
	if e == nil {
		return nil
	}
	return e.Code
}
