/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"encoding/json"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/utils"
)

// GenerateTrackResponseType - The type of track generated ("subtitle").
type GenerateTrackResponseType string

const (
	GenerateTrackResponseTypeSubtitle GenerateTrackResponseType = "subtitle"
)

func (e GenerateTrackResponseType) ToPointer() *GenerateTrackResponseType {
	return &e
}
func (e *GenerateTrackResponseType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "subtitle":
		*e = GenerateTrackResponseType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GenerateTrackResponseType: %v", v)
	}
}

// GenerateTrackResponseLanguageCode - The BCP 47 language code representing the language of the generated track.
type GenerateTrackResponseLanguageCode string

const (
	GenerateTrackResponseLanguageCodeArSa GenerateTrackResponseLanguageCode = "ar-SA"
	GenerateTrackResponseLanguageCodeBnBd GenerateTrackResponseLanguageCode = "bn-BD"
	GenerateTrackResponseLanguageCodeBnIn GenerateTrackResponseLanguageCode = "bn-IN"
	GenerateTrackResponseLanguageCodeCaEs GenerateTrackResponseLanguageCode = "ca-ES"
	GenerateTrackResponseLanguageCodeCsCz GenerateTrackResponseLanguageCode = "cs-CZ"
	GenerateTrackResponseLanguageCodeDaDk GenerateTrackResponseLanguageCode = "da-DK"
	GenerateTrackResponseLanguageCodeDeAt GenerateTrackResponseLanguageCode = "de-AT"
	GenerateTrackResponseLanguageCodeDeCh GenerateTrackResponseLanguageCode = "de-CH"
	GenerateTrackResponseLanguageCodeDeDe GenerateTrackResponseLanguageCode = "de-DE"
	GenerateTrackResponseLanguageCodeElGr GenerateTrackResponseLanguageCode = "el-GR"
	GenerateTrackResponseLanguageCodeEnAu GenerateTrackResponseLanguageCode = "en-AU"
	GenerateTrackResponseLanguageCodeEnCa GenerateTrackResponseLanguageCode = "en-CA"
	GenerateTrackResponseLanguageCodeEnGb GenerateTrackResponseLanguageCode = "en-GB"
	GenerateTrackResponseLanguageCodeEnIe GenerateTrackResponseLanguageCode = "en-IE"
	GenerateTrackResponseLanguageCodeEnIn GenerateTrackResponseLanguageCode = "en-IN"
	GenerateTrackResponseLanguageCodeEnNz GenerateTrackResponseLanguageCode = "en-NZ"
	GenerateTrackResponseLanguageCodeEnUs GenerateTrackResponseLanguageCode = "en-US"
	GenerateTrackResponseLanguageCodeEnZa GenerateTrackResponseLanguageCode = "en-ZA"
	GenerateTrackResponseLanguageCodeEsAr GenerateTrackResponseLanguageCode = "es-AR"
	GenerateTrackResponseLanguageCodeEsCl GenerateTrackResponseLanguageCode = "es-CL"
	GenerateTrackResponseLanguageCodeEsCo GenerateTrackResponseLanguageCode = "es-CO"
	GenerateTrackResponseLanguageCodeEsEs GenerateTrackResponseLanguageCode = "es-ES"
	GenerateTrackResponseLanguageCodeEsMx GenerateTrackResponseLanguageCode = "es-MX"
	GenerateTrackResponseLanguageCodeEsUs GenerateTrackResponseLanguageCode = "es-US"
	GenerateTrackResponseLanguageCodeFiFi GenerateTrackResponseLanguageCode = "fi-FI"
	GenerateTrackResponseLanguageCodeFrBe GenerateTrackResponseLanguageCode = "fr-BE"
	GenerateTrackResponseLanguageCodeFrCa GenerateTrackResponseLanguageCode = "fr-CA"
	GenerateTrackResponseLanguageCodeFrCh GenerateTrackResponseLanguageCode = "fr-CH"
	GenerateTrackResponseLanguageCodeFrFr GenerateTrackResponseLanguageCode = "fr-FR"
	GenerateTrackResponseLanguageCodeHeIl GenerateTrackResponseLanguageCode = "he-IL"
	GenerateTrackResponseLanguageCodeHiIn GenerateTrackResponseLanguageCode = "hi-IN"
	GenerateTrackResponseLanguageCodeHrHr GenerateTrackResponseLanguageCode = "hr-HR"
	GenerateTrackResponseLanguageCodeHuHu GenerateTrackResponseLanguageCode = "hu-HU"
	GenerateTrackResponseLanguageCodeIDID GenerateTrackResponseLanguageCode = "id-ID"
	GenerateTrackResponseLanguageCodeItCh GenerateTrackResponseLanguageCode = "it-CH"
	GenerateTrackResponseLanguageCodeItIt GenerateTrackResponseLanguageCode = "it-IT"
	GenerateTrackResponseLanguageCodeJaJp GenerateTrackResponseLanguageCode = "ja-JP"
	GenerateTrackResponseLanguageCodeKoKr GenerateTrackResponseLanguageCode = "ko-KR"
	GenerateTrackResponseLanguageCodeNlBe GenerateTrackResponseLanguageCode = "nl-BE"
	GenerateTrackResponseLanguageCodeNlNl GenerateTrackResponseLanguageCode = "nl-NL"
	GenerateTrackResponseLanguageCodeNoNo GenerateTrackResponseLanguageCode = "no-NO"
	GenerateTrackResponseLanguageCodePlPl GenerateTrackResponseLanguageCode = "pl-PL"
	GenerateTrackResponseLanguageCodePtBr GenerateTrackResponseLanguageCode = "pt-BR"
	GenerateTrackResponseLanguageCodePtPt GenerateTrackResponseLanguageCode = "pt-PT"
	GenerateTrackResponseLanguageCodeRoRo GenerateTrackResponseLanguageCode = "ro-RO"
	GenerateTrackResponseLanguageCodeRuRu GenerateTrackResponseLanguageCode = "ru-RU"
	GenerateTrackResponseLanguageCodeSkSk GenerateTrackResponseLanguageCode = "sk-SK"
	GenerateTrackResponseLanguageCodeSvSe GenerateTrackResponseLanguageCode = "sv-SE"
	GenerateTrackResponseLanguageCodeTaIn GenerateTrackResponseLanguageCode = "ta-IN"
	GenerateTrackResponseLanguageCodeTaLk GenerateTrackResponseLanguageCode = "ta-LK"
	GenerateTrackResponseLanguageCodeThTh GenerateTrackResponseLanguageCode = "th-TH"
	GenerateTrackResponseLanguageCodeTrTr GenerateTrackResponseLanguageCode = "tr-TR"
	GenerateTrackResponseLanguageCodeUkUa GenerateTrackResponseLanguageCode = "uk-UA"
	GenerateTrackResponseLanguageCodeBgBg GenerateTrackResponseLanguageCode = "bg-BG"
	GenerateTrackResponseLanguageCodeZhCn GenerateTrackResponseLanguageCode = "zh-CN"
	GenerateTrackResponseLanguageCodeZhHk GenerateTrackResponseLanguageCode = "zh-HK"
	GenerateTrackResponseLanguageCodeZhTw GenerateTrackResponseLanguageCode = "zh-TW"
)

func (e GenerateTrackResponseLanguageCode) ToPointer() *GenerateTrackResponseLanguageCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GenerateTrackResponseLanguageCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "ar-SA", "bn-BD", "bn-IN", "ca-ES", "cs-CZ", "da-DK", "de-AT", "de-CH", "de-DE", "el-GR", "en-AU", "en-CA", "en-GB", "en-IE", "en-IN", "en-NZ", "en-US", "en-ZA", "es-AR", "es-CL", "es-CO", "es-ES", "es-MX", "es-US", "fi-FI", "fr-BE", "fr-CA", "fr-CH", "fr-FR", "he-IL", "hi-IN", "hr-HR", "hu-HU", "id-ID", "it-CH", "it-IT", "ja-JP", "ko-KR", "nl-BE", "nl-NL", "no-NO", "pl-PL", "pt-BR", "pt-PT", "ro-RO", "ru-RU", "sk-SK", "sv-SE", "ta-IN", "ta-LK", "th-TH", "tr-TR", "uk-UA", "bg-BG", "zh-CN", "zh-HK", "zh-TW":
			return true
		}
	}
	return false
}

// GenerateTrackResponse - Represents the response for a successfully generated subtitle track.
type GenerateTrackResponse struct {
	// A unique identifier for the generated track.
	ID *string `json:"id,omitzero"`
	// The type of track generated ("subtitle").
	Type *GenerateTrackResponseType `json:"type,omitzero"`
	// The BCP 47 language code representing the language of the generated track.
	//
	LanguageCode *GenerateTrackResponseLanguageCode `json:"languageCode,omitzero"`
	// The full name of the language for the generated track.
	LanguageName *string `json:"languageName,omitzero"`
	// You can search for videos with specific key value pairs using metadata, when you tag a video in "key" : "value" pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
	//
	Metadata map[string]string `json:"metadata,omitzero"`
}

func (g GenerateTrackResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GenerateTrackResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GenerateTrackResponse) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GenerateTrackResponse) GetType() *GenerateTrackResponseType {
	if g == nil {
		return nil
	}
	return g.Type
}

func (g *GenerateTrackResponse) GetLanguageCode() *GenerateTrackResponseLanguageCode {
	if g == nil {
		return nil
	}
	return g.LanguageCode
}

func (g *GenerateTrackResponse) GetLanguageName() *string {
	if g == nil {
		return nil
	}
	return g.LanguageName
}

func (g *GenerateTrackResponse) GetMetadata() map[string]string {
	if g == nil {
		return nil
	}
	return g.Metadata
}
