/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
	"time"
)

// GetAllSigningKeysResponseDto - Displays the result of the request.
type GetAllSigningKeysResponseDto struct {
	// A unique identifier is generated by FastPix for the signing keys.
	ID *string `json:"id,omitzero"`
	// Time the Signing key was generated, defined as a localDateTime (UTC Time).
	CreatedAt *time.Time `json:"createdAt,omitzero"`
}

func (g GetAllSigningKeysResponseDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAllSigningKeysResponseDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAllSigningKeysResponseDto) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GetAllSigningKeysResponseDto) GetCreatedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.CreatedAt
}
