// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
	"time"
)

// GetCreateLiveStreamResponseDTOMetadata - You can search for videos with specific key value pairs using metadata, when you tag a video in "key":"value"s pairs. Dynamic Metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
type GetCreateLiveStreamResponseDTOMetadata struct {
}

// GetCreateLiveStreamResponseDTOSrtPlaybackResponse - This object contains the livestream playback response details for SRT Protocol.
type GetCreateLiveStreamResponseDTOSrtPlaybackResponse struct {
	// A unique identifier for the SRT playback stream. This ID is used to distinguish between different playback streams.
	SrtPlaybackStreamID *string `json:"srtPlaybackStreamId,omitempty"`
	// A playback secret used for securing the SRT playback stream. This ensures that only authorized users can access the playback.
	SrtPlaybackSecret *string `json:"srtPlaybackSecret,omitempty"`
}

func (o *GetCreateLiveStreamResponseDTOSrtPlaybackResponse) GetSrtPlaybackStreamID() *string {
	if o == nil {
		return nil
	}
	return o.SrtPlaybackStreamID
}

func (o *GetCreateLiveStreamResponseDTOSrtPlaybackResponse) GetSrtPlaybackSecret() *string {
	if o == nil {
		return nil
	}
	return o.SrtPlaybackSecret
}

// GetCreateLiveStreamResponseDTO - Displays the result of the request.
type GetCreateLiveStreamResponseDTO struct {
	// Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
	StreamID *string `json:"streamId,omitempty"`
	// A unique stream key is generated for streaming, allowing the user to start streaming on any third-party platform using this key.
	StreamKey *string `json:"streamKey,omitempty"`
	// A secret used for securing the SRT stream. This ensures that only authorized users can access the stream.
	SrtSecret *string `json:"srtSecret,omitempty"`
	// FastPix allows for a to trial the live stream for free. The duration of trial streams is five minutes. After five minutes of activity, the trial stream is turned off, and the recorded asset is removed after a day.
	Trial *bool `json:"trial,omitempty"`
	// The current live stream status can be one of four values:Idle, Preparing, Active or Disabled.The Idle status signifies that there isn't a broadcast in progress.The preparing status indicates that the stream is getting prepared. while, the Active status indicates that a broadcast is currently in progress. The Disabled status means that no more RTMP streams can be published.
	Status *string `json:"status,omitempty"`
	// Max resolution can be used to control the maximum resolution your media is encoded, stored, and streamed at.
	MaxResolution *string `json:"maxResolution,omitempty"`
	// The maximum duration in seconds that a live stream can have before it ends the stream.
	MaxDuration *int64 `json:"maxDuration,omitempty"`
	// It is the moment when the stream was created Time the media was generated, defined as a localDateTime (UTC Time).
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// In case the software streaming the live, get disrupted for any reason and get disconnect from FastPix, the reconnect window specifies the waiting time span of FastPix will wait before ending the stream. Before starting the stream, you can set the reconnect window time set which is up to 1800 seconds.
	ReconnectWindow *int64 `default:"60" json:"reconnectWindow"`
	// When set to true, the livestream will be recorded and stored for later viewing purposes. If set to false, the livestream will not be recorded.
	EnableRecording *bool `json:"enableRecording,omitempty"`
	// Determines whether the recorded stream should be publicly accessible or private in Live to VOD (Video on Demand).
	MediaPolicy *string `json:"mediaPolicy,omitempty"`
	// You can search for videos with specific key value pairs using metadata, when you tag a video in "key":"value"s pairs. Dynamic Metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
	Metadata *GetCreateLiveStreamResponseDTOMetadata `json:"metadata,omitempty"`
	// A collection of Playback ID objects utilized for crafting HLS playback urls.
	PlaybackID []PlaybackIds `json:"playbackId,omitempty"`
	// This object contains the livestream playback response details for SRT Protocol.
	SrtPlaybackResponse *GetCreateLiveStreamResponseDTOSrtPlaybackResponse `json:"srtPlaybackResponse,omitempty"`
}

func (g GetCreateLiveStreamResponseDTO) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreateLiveStreamResponseDTO) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetCreateLiveStreamResponseDTO) GetStreamID() *string {
	if o == nil {
		return nil
	}
	return o.StreamID
}

func (o *GetCreateLiveStreamResponseDTO) GetStreamKey() *string {
	if o == nil {
		return nil
	}
	return o.StreamKey
}

func (o *GetCreateLiveStreamResponseDTO) GetSrtSecret() *string {
	if o == nil {
		return nil
	}
	return o.SrtSecret
}

func (o *GetCreateLiveStreamResponseDTO) GetTrial() *bool {
	if o == nil {
		return nil
	}
	return o.Trial
}

func (o *GetCreateLiveStreamResponseDTO) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetCreateLiveStreamResponseDTO) GetMaxResolution() *string {
	if o == nil {
		return nil
	}
	return o.MaxResolution
}

func (o *GetCreateLiveStreamResponseDTO) GetMaxDuration() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxDuration
}

func (o *GetCreateLiveStreamResponseDTO) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *GetCreateLiveStreamResponseDTO) GetReconnectWindow() *int64 {
	if o == nil {
		return nil
	}
	return o.ReconnectWindow
}

func (o *GetCreateLiveStreamResponseDTO) GetEnableRecording() *bool {
	if o == nil {
		return nil
	}
	return o.EnableRecording
}

func (o *GetCreateLiveStreamResponseDTO) GetMediaPolicy() *string {
	if o == nil {
		return nil
	}
	return o.MediaPolicy
}

func (o *GetCreateLiveStreamResponseDTO) GetMetadata() *GetCreateLiveStreamResponseDTOMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *GetCreateLiveStreamResponseDTO) GetPlaybackID() []PlaybackIds {
	if o == nil {
		return nil
	}
	return o.PlaybackID
}

func (o *GetCreateLiveStreamResponseDTO) GetSrtPlaybackResponse() *GetCreateLiveStreamResponseDTOSrtPlaybackResponse {
	if o == nil {
		return nil
	}
	return o.SrtPlaybackResponse
}
