/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
)

// GetPublicPemUsingSigningKeyIDResponseDTOData - Displays the result of the request.
type GetPublicPemUsingSigningKeyIDResponseDTOData struct {
	// FastPix generates a unique identifier for each workspace.
	WorkspaceID  *string `json:"workspaceId,omitzero"`
	SigningKeyID *string `json:"signingKeyId,omitzero"`
	// A public key is a byte encoded key used to create a signed JSON Web Token (JWT) for authentication.
	PublicKey *string `json:"publicKey,omitzero"`
}

func (g *GetPublicPemUsingSigningKeyIDResponseDTOData) GetWorkspaceID() *string {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}

func (g *GetPublicPemUsingSigningKeyIDResponseDTOData) GetSigningKeyID() *string {
	if g == nil {
		return nil
	}
	return g.SigningKeyID
}

func (g *GetPublicPemUsingSigningKeyIDResponseDTOData) GetPublicKey() *string {
	if g == nil {
		return nil
	}
	return g.PublicKey
}

// GetPublicPemUsingSigningKeyIDResponseDTO - Displays the result of the request.
type GetPublicPemUsingSigningKeyIDResponseDTO struct {
	// Shows the request status. Returns true for success and false for failure.
	Success *bool `json:"success,omitzero"`
	// Displays the result of the request.
	Data *GetPublicPemUsingSigningKeyIDResponseDTOData `json:"data,omitzero"`
}

func (g GetPublicPemUsingSigningKeyIDResponseDTO) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPublicPemUsingSigningKeyIDResponseDTO) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPublicPemUsingSigningKeyIDResponseDTO) GetSuccess() *bool {
	if g == nil {
		return nil
	}
	return g.Success
}

func (g *GetPublicPemUsingSigningKeyIDResponseDTO) GetData() *GetPublicPemUsingSigningKeyIDResponseDTOData {
	if g == nil {
		return nil
	}
	return g.Data
}
