// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// LiveStreamResponseDTO - Displays the result of the request.
type LiveStreamResponseDTO struct {
	// It demonstrates whether the request is successful or not.
	Success *bool `json:"success,omitempty"`
	// Displays the result of the request.
	Data *GetCreateLiveStreamResponseDTO `json:"data,omitempty"`
}

func (o *LiveStreamResponseDTO) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *LiveStreamResponseDTO) GetData() *GetCreateLiveStreamResponseDTO {
	if o == nil {
		return nil
	}
	return o.Data
}
