/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
)

// LivestreamgetResponse - Displays the result of the request.
type LivestreamgetResponse struct {
	// Shows the request status. Returns true for success and false for failure.
	Success *bool `json:"success,omitzero"`
	// Displays the result of the request.
	Data *GetCreateLiveStreamResponseDTO `json:"data,omitzero"`
}

func (l LivestreamgetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LivestreamgetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LivestreamgetResponse) GetSuccess() *bool {
	if l == nil {
		return nil
	}
	return l.Success
}

func (l *LivestreamgetResponse) GetData() *GetCreateLiveStreamResponseDTO {
	if l == nil {
		return nil
	}
	return l.Data
}
