/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"errors"
	"fmt"
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/optionalnullable"
	"time"
)

// LiveMediaClipsMaxResolution - The maximum resolution specified by the user for the media.
type LiveMediaClipsMaxResolution string

const (
	LiveMediaClipsMaxResolutionTwoThousandOneHundredAndSixtyp  LiveMediaClipsMaxResolution = "2160p"
	LiveMediaClipsMaxResolutionOneThousandFourHundredAndFortyp LiveMediaClipsMaxResolution = "1440p"
	LiveMediaClipsMaxResolutionOneThousandAndEightyp           LiveMediaClipsMaxResolution = "1080p"
	LiveMediaClipsMaxResolutionSevenHundredAndTwentyp          LiveMediaClipsMaxResolution = "720p"
	LiveMediaClipsMaxResolutionFourHundredAndEightyp           LiveMediaClipsMaxResolution = "480p"
)

func (e LiveMediaClipsMaxResolution) ToPointer() *LiveMediaClipsMaxResolution {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LiveMediaClipsMaxResolution) IsExact() bool {
	if e != nil {
		switch *e {
		case "2160p", "1440p", "1080p", "720p", "480p":
			return true
		}
	}
	return false
}

// LiveMediaClipsSourceResolution - The actual resolution of the uploaded media. This represents the native quality of the source media.
type LiveMediaClipsSourceResolution string

const (
	LiveMediaClipsSourceResolutionTwoThousandOneHundredAndSixtyp  LiveMediaClipsSourceResolution = "2160p"
	LiveMediaClipsSourceResolutionTwoThousandOneHundredAndSixty   LiveMediaClipsSourceResolution = "2160"
	LiveMediaClipsSourceResolutionOneThousandFourHundredAndFortyp LiveMediaClipsSourceResolution = "1440p"
	LiveMediaClipsSourceResolutionOneThousandFourHundredAndForty  LiveMediaClipsSourceResolution = "1440"
	LiveMediaClipsSourceResolutionOneThousandAndEightyp           LiveMediaClipsSourceResolution = "1080p"
	LiveMediaClipsSourceResolutionOneThousandAndEighty            LiveMediaClipsSourceResolution = "1080"
	LiveMediaClipsSourceResolutionSevenHundredAndTwentyp          LiveMediaClipsSourceResolution = "720p"
	LiveMediaClipsSourceResolutionSevenHundredAndTwenty           LiveMediaClipsSourceResolution = "720"
	LiveMediaClipsSourceResolutionFourHundredAndEightyp           LiveMediaClipsSourceResolution = "480p"
	LiveMediaClipsSourceResolutionFourHundredAndEighty            LiveMediaClipsSourceResolution = "480"
)

func (e LiveMediaClipsSourceResolution) ToPointer() *LiveMediaClipsSourceResolution {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LiveMediaClipsSourceResolution) IsExact() bool {
	if e != nil {
		switch *e {
		case "2160p", "2160", "1440p", "1440", "1080p", "1080", "720p", "720", "480p", "480":
			return true
		}
	}
	return false
}

// LiveMediaClipsStatus - Determines the media's status, which can be one of the possible values.
type LiveMediaClipsStatus string

const (
	LiveMediaClipsStatusCreated     LiveMediaClipsStatus = "Created"
	LiveMediaClipsStatusDownloading LiveMediaClipsStatus = "Downloading"
	LiveMediaClipsStatusDownloaded  LiveMediaClipsStatus = "Downloaded"
	LiveMediaClipsStatusValidating  LiveMediaClipsStatus = "Validating"
	LiveMediaClipsStatusInQueue     LiveMediaClipsStatus = "In Queue"
	LiveMediaClipsStatusProcessing  LiveMediaClipsStatus = "Processing"
	LiveMediaClipsStatusReady       LiveMediaClipsStatus = "Ready"
	LiveMediaClipsStatusFailed      LiveMediaClipsStatus = "Failed"
)

func (e LiveMediaClipsStatus) ToPointer() *LiveMediaClipsStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LiveMediaClipsStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "Created", "Downloading", "Downloaded", "Validating", "In Queue", "Processing", "Ready", "Failed":
			return true
		}
	}
	return false
}

type LiveMediaClipsTrackType string

const (
	LiveMediaClipsTrackTypeVideoTrack    LiveMediaClipsTrackType = "VideoTrack"
	LiveMediaClipsTrackTypeAudioTrack    LiveMediaClipsTrackType = "AudioTrack"
	LiveMediaClipsTrackTypeSubtitleTrack LiveMediaClipsTrackType = "SubtitleTrack"
)

type LiveMediaClipsTrack struct {
	VideoTrack    *VideoTrack    `queryParam:"inline" union:"member"`
	AudioTrack    *AudioTrack    `queryParam:"inline" union:"member"`
	SubtitleTrack *SubtitleTrack `queryParam:"inline" union:"member"`

	Type LiveMediaClipsTrackType
}

func CreateLiveMediaClipsTrackVideoTrack(videoTrack VideoTrack) LiveMediaClipsTrack {
	typ := LiveMediaClipsTrackTypeVideoTrack

	return LiveMediaClipsTrack{
		VideoTrack: &videoTrack,
		Type:       typ,
	}
}

func CreateLiveMediaClipsTrackAudioTrack(audioTrack AudioTrack) LiveMediaClipsTrack {
	typ := LiveMediaClipsTrackTypeAudioTrack

	return LiveMediaClipsTrack{
		AudioTrack: &audioTrack,
		Type:       typ,
	}
}

func CreateLiveMediaClipsTrackSubtitleTrack(subtitleTrack SubtitleTrack) LiveMediaClipsTrack {
	typ := LiveMediaClipsTrackTypeSubtitleTrack

	return LiveMediaClipsTrack{
		SubtitleTrack: &subtitleTrack,
		Type:          typ,
	}
}

func (u *LiveMediaClipsTrack) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var videoTrack VideoTrack = VideoTrack{}
	if err := utils.UnmarshalJSON(data, &videoTrack, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  LiveMediaClipsTrackTypeVideoTrack,
			Value: &videoTrack,
		})
	}

	var audioTrack AudioTrack = AudioTrack{}
	if err := utils.UnmarshalJSON(data, &audioTrack, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  LiveMediaClipsTrackTypeAudioTrack,
			Value: &audioTrack,
		})
	}

	var subtitleTrack SubtitleTrack = SubtitleTrack{}
	if err := utils.UnmarshalJSON(data, &subtitleTrack, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  LiveMediaClipsTrackTypeSubtitleTrack,
			Value: &subtitleTrack,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for LiveMediaClipsTrack", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for LiveMediaClipsTrack", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(LiveMediaClipsTrackType)
	switch best.Type {
	case LiveMediaClipsTrackTypeVideoTrack:
		u.VideoTrack = best.Value.(*VideoTrack)
		return nil
	case LiveMediaClipsTrackTypeAudioTrack:
		u.AudioTrack = best.Value.(*AudioTrack)
		return nil
	case LiveMediaClipsTrackTypeSubtitleTrack:
		u.SubtitleTrack = best.Value.(*SubtitleTrack)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for LiveMediaClipsTrack", string(data))
}

func (u LiveMediaClipsTrack) MarshalJSON() ([]byte, error) {
	if u.VideoTrack != nil {
		return utils.MarshalJSON(u.VideoTrack, "", true)
	}

	if u.AudioTrack != nil {
		return utils.MarshalJSON(u.AudioTrack, "", true)
	}

	if u.SubtitleTrack != nil {
		return utils.MarshalJSON(u.SubtitleTrack, "", true)
	}

	return nil, errors.New("could not marshal union type LiveMediaClipsTrack: all fields are null")
}

// LiveMediaClipsMp4Support - Determines the type of MP4 support for the media.
// - **none**: Disables MP4 support.
// - **capped_4k**: Enables MP4 downloads with resolutions up to 4K.
// - **audioOnly**: Provides an MP4 stream containing only the audio.
// - **audioOnly,capped_4k**: Enables both MP4 video downloads (up to 4K) and an audio-only stream.
type LiveMediaClipsMp4Support string

const (
	LiveMediaClipsMp4SupportNone              LiveMediaClipsMp4Support = "none"
	LiveMediaClipsMp4SupportCapped4k          LiveMediaClipsMp4Support = "capped_4k"
	LiveMediaClipsMp4SupportAudioOnly         LiveMediaClipsMp4Support = "audioOnly"
	LiveMediaClipsMp4SupportAudioOnlyCapped4k LiveMediaClipsMp4Support = "audioOnly,capped_4k"
)

func (e LiveMediaClipsMp4Support) ToPointer() *LiveMediaClipsMp4Support {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LiveMediaClipsMp4Support) IsExact() bool {
	if e != nil {
		switch *e {
		case "none", "capped_4k", "audioOnly", "audioOnly,capped_4k":
			return true
		}
	}
	return false
}

type LiveMediaClips struct {
	// A video thumbnail is a still image that acts as the preview image for your video.
	Thumbnail optionalnullable.OptionalNullable[string] `json:"thumbnail,omitzero"`
	// The unique identifier assigned to the media when created. The value must be a valid UUID.
	ID *string `json:"id,omitzero"`
	// A unique identifier is generated by FastPix for the workspace.
	WorkspaceID *string `json:"workspaceId,omitzero"`
	// The ID of the livestream for which the clips were created.
	StreamID *string `json:"streamId,omitzero"`
	// The unique identifier of the user who created this media.
	CreatorID *string `json:"creatorId,omitzero"`
	// Title of the media file.
	Title optionalnullable.OptionalNullable[string] `json:"title,omitzero"`
	// The maximum resolution specified by the user for the media.
	MaxResolution *LiveMediaClipsMaxResolution `default:"1080p" json:"maxResolution"`
	// The actual resolution of the uploaded media. This represents the native quality of the source media.
	SourceResolution *LiveMediaClipsSourceResolution `default:"1080p" json:"sourceResolution"`
	// Determines the media's status, which can be one of the possible values.
	Status *LiveMediaClipsStatus `json:"status,omitzero"`
	// The sourceAccess parameter determines whether the original media file is accessible. Set to true to enable access or false to restrict it.
	SourceAccess *bool `json:"sourceAccess,omitzero"`
	// A collection of Playback ID objects utilized for crafting HLS playback URLs.
	PlaybackIds []PlaybackID `json:"playbackIds,omitzero"`
	// A media consists of different media tracks, like video, audio, and subtitle, all combined.
	Tracks []LiveMediaClipsTrack `json:"tracks,omitzero"`
	// Determines the type of MP4 support for the media.
	// - **none**: Disables MP4 support.
	// - **capped_4k**: Enables MP4 downloads with resolutions up to 4K.
	// - **audioOnly**: Provides an MP4 stream containing only the audio.
	// - **audioOnly,capped_4k**: Enables both MP4 video downloads (up to 4K) and an audio-only stream.
	//
	Mp4Support *LiveMediaClipsMp4Support `json:"mp4Support,omitzero"`
	// List of generated subtitle tracks associated with the media.
	GeneratedSubtitles optionalnullable.OptionalNullable[[]TracksSubtitles] `json:"generatedSubtitles,omitzero"`
	// Indicates whether the media contains only audio (no video track).
	IsAudioOnly optionalnullable.OptionalNullable[bool] `json:"isAudioOnly,omitzero"`
	// Indicates whether subtitles are available for the media.
	SubtitleAvailable optionalnullable.OptionalNullable[bool] `json:"subtitleAvailable,omitzero"`
	// The length of the media in seconds, with a maximum allowed duration of 12 hours per individual media.
	Duration *string `json:"duration,omitzero"`
	// The aspect ratio of a video is a value that describes the relative shape of a video based on its width and height.
	AspectRatio optionalnullable.OptionalNullable[string] `json:"aspectRatio,omitzero"`
	// Time the media was created, defined as a localDateTime (UTC Time).
	CreatedAt *time.Time `json:"createdAt,omitzero"`
	// Time the media was updated, defined as a localDateTime (UTC Time).
	UpdatedAt *time.Time `json:"updatedAt,omitzero"`
}

func (l LiveMediaClips) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LiveMediaClips) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LiveMediaClips) GetThumbnail() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.Thumbnail
}

func (l *LiveMediaClips) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *LiveMediaClips) GetWorkspaceID() *string {
	if l == nil {
		return nil
	}
	return l.WorkspaceID
}

func (l *LiveMediaClips) GetStreamID() *string {
	if l == nil {
		return nil
	}
	return l.StreamID
}

func (l *LiveMediaClips) GetCreatorID() *string {
	if l == nil {
		return nil
	}
	return l.CreatorID
}

func (l *LiveMediaClips) GetTitle() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.Title
}

func (l *LiveMediaClips) GetMaxResolution() *LiveMediaClipsMaxResolution {
	if l == nil {
		return nil
	}
	return l.MaxResolution
}

func (l *LiveMediaClips) GetSourceResolution() *LiveMediaClipsSourceResolution {
	if l == nil {
		return nil
	}
	return l.SourceResolution
}

func (l *LiveMediaClips) GetStatus() *LiveMediaClipsStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *LiveMediaClips) GetSourceAccess() *bool {
	if l == nil {
		return nil
	}
	return l.SourceAccess
}

func (l *LiveMediaClips) GetPlaybackIds() []PlaybackID {
	if l == nil {
		return nil
	}
	return l.PlaybackIds
}

func (l *LiveMediaClips) GetTracks() []LiveMediaClipsTrack {
	if l == nil {
		return nil
	}
	return l.Tracks
}

func (l *LiveMediaClips) GetMp4Support() *LiveMediaClipsMp4Support {
	if l == nil {
		return nil
	}
	return l.Mp4Support
}

func (l *LiveMediaClips) GetGeneratedSubtitles() optionalnullable.OptionalNullable[[]TracksSubtitles] {
	if l == nil {
		return nil
	}
	return l.GeneratedSubtitles
}

func (l *LiveMediaClips) GetIsAudioOnly() optionalnullable.OptionalNullable[bool] {
	if l == nil {
		return nil
	}
	return l.IsAudioOnly
}

func (l *LiveMediaClips) GetSubtitleAvailable() optionalnullable.OptionalNullable[bool] {
	if l == nil {
		return nil
	}
	return l.SubtitleAvailable
}

func (l *LiveMediaClips) GetDuration() *string {
	if l == nil {
		return nil
	}
	return l.Duration
}

func (l *LiveMediaClips) GetAspectRatio() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.AspectRatio
}

func (l *LiveMediaClips) GetCreatedAt() *time.Time {
	if l == nil {
		return nil
	}
	return l.CreatedAt
}

func (l *LiveMediaClips) GetUpdatedAt() *time.Time {
	if l == nil {
		return nil
	}
	return l.UpdatedAt
}
