/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
	"time"
)

// MediaClipResponseStatus - The current processing status of the media.
type MediaClipResponseStatus string

const (
	MediaClipResponseStatusCreated     MediaClipResponseStatus = "Created"
	MediaClipResponseStatusDownloading MediaClipResponseStatus = "Downloading"
	MediaClipResponseStatusDownloaded  MediaClipResponseStatus = "Downloaded"
	MediaClipResponseStatusValidating  MediaClipResponseStatus = "Validating"
	MediaClipResponseStatusInQueue     MediaClipResponseStatus = "In Queue"
	MediaClipResponseStatusProcessing  MediaClipResponseStatus = "Processing"
	MediaClipResponseStatusReady       MediaClipResponseStatus = "Ready"
	MediaClipResponseStatusFailed      MediaClipResponseStatus = "Failed"
)

func (e MediaClipResponseStatus) ToPointer() *MediaClipResponseStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MediaClipResponseStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "Created", "Downloading", "Downloaded", "Validating", "In Queue", "Processing", "Ready", "Failed":
			return true
		}
	}
	return false
}

type MediaClipResponsePlaybackID struct {
	// The unique identifier for playback.
	ID *string `json:"id,omitzero"`
	// The access policy of the playback.
	AccessPolicy *string `json:"accessPolicy,omitzero"`
}

func (m *MediaClipResponsePlaybackID) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *MediaClipResponsePlaybackID) GetAccessPolicy() *string {
	if m == nil {
		return nil
	}
	return m.AccessPolicy
}

type MediaClipResponseData struct {
	// The unique identifier assigned to the media by FastPix.
	ID *string `json:"id,omitzero"`
	// Duration of the media in HH:MM:SS format.
	Duration *string `json:"duration,omitzero"`
	// The current processing status of the media.
	Status *MediaClipResponseStatus `json:"status,omitzero"`
	// A video thumbnail that acts as a preview image for the video.
	Thumbnail *string `json:"thumbnail,omitzero"`
	// Timestamp of when the media was created.
	CreatedAt   *time.Time                    `json:"createdAt,omitzero"`
	PlaybackIds []MediaClipResponsePlaybackID `json:"playbackIds,omitzero"`
}

func (m MediaClipResponseData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MediaClipResponseData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MediaClipResponseData) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *MediaClipResponseData) GetDuration() *string {
	if m == nil {
		return nil
	}
	return m.Duration
}

func (m *MediaClipResponseData) GetStatus() *MediaClipResponseStatus {
	if m == nil {
		return nil
	}
	return m.Status
}

func (m *MediaClipResponseData) GetThumbnail() *string {
	if m == nil {
		return nil
	}
	return m.Thumbnail
}

func (m *MediaClipResponseData) GetCreatedAt() *time.Time {
	if m == nil {
		return nil
	}
	return m.CreatedAt
}

func (m *MediaClipResponseData) GetPlaybackIds() []MediaClipResponsePlaybackID {
	if m == nil {
		return nil
	}
	return m.PlaybackIds
}

type MediaClipResponsePagination struct {
	// Total number of records available.
	TotalRecords *int64 `json:"totalRecords,omitzero"`
	// The starting offset of the current result set.
	CurrentOffset *int64 `json:"currentOffset,omitzero"`
	// The number of items returned in the current response.
	OffsetCount *int64 `json:"offsetCount,omitzero"`
}

func (m *MediaClipResponsePagination) GetTotalRecords() *int64 {
	if m == nil {
		return nil
	}
	return m.TotalRecords
}

func (m *MediaClipResponsePagination) GetCurrentOffset() *int64 {
	if m == nil {
		return nil
	}
	return m.CurrentOffset
}

func (m *MediaClipResponsePagination) GetOffsetCount() *int64 {
	if m == nil {
		return nil
	}
	return m.OffsetCount
}

type MediaClipResponse struct {
	// Shows the request status. Returns true for success and false for failure.
	Success    *bool                        `json:"success,omitzero"`
	Data       []MediaClipResponseData      `json:"data,omitzero"`
	Pagination *MediaClipResponsePagination `json:"pagination,omitzero"`
}

func (m MediaClipResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MediaClipResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MediaClipResponse) GetSuccess() *bool {
	if m == nil {
		return nil
	}
	return m.Success
}

func (m *MediaClipResponse) GetData() []MediaClipResponseData {
	if m == nil {
		return nil
	}
	return m.Data
}

func (m *MediaClipResponse) GetPagination() *MediaClipResponsePagination {
	if m == nil {
		return nil
	}
	return m.Pagination
}
