/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
	"github.com/FastPix/fastpix-go/optionalnullable"
)

// MetricsComparisonDetails - Compare multiple metrics across specified dimensions.
type MetricsComparisonDetails struct {
	// The specific metric value calculated based on the applied filters.
	Value *float64 `json:"value,omitzero"`
	// value can be score that ranges from 0 to 100
	Type *string `json:"type,omitzero"`
	// value can be score that ranges from 0 to 100
	Name *string `json:"name,omitzero"`
	// The metric field represents the name of the Key Performance Indicator (KPI) being tracked or analyzed. It identifies a specific measurable aspect of the video playback experience, such as buffering time, video start failure rate, or playback quality.
	//
	Metric *string `json:"metric,omitzero"`
	// value can be avg, sum, count or 95th
	Measurement optionalnullable.OptionalNullable[string] `json:"measurement,omitzero"`
	// Nested comparison items
	Items optionalnullable.OptionalNullable[[]MetricsComparisonDetails] `json:"items,omitzero"`
}

func (m MetricsComparisonDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetricsComparisonDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MetricsComparisonDetails) GetValue() *float64 {
	if m == nil {
		return nil
	}
	return m.Value
}

func (m *MetricsComparisonDetails) GetType() *string {
	if m == nil {
		return nil
	}
	return m.Type
}

func (m *MetricsComparisonDetails) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MetricsComparisonDetails) GetMetric() *string {
	if m == nil {
		return nil
	}
	return m.Metric
}

func (m *MetricsComparisonDetails) GetMeasurement() optionalnullable.OptionalNullable[string] {
	if m == nil {
		return nil
	}
	return m.Measurement
}

func (m *MetricsComparisonDetails) GetItems() optionalnullable.OptionalNullable[[]MetricsComparisonDetails] {
	if m == nil {
		return nil
	}
	return m.Items
}
