/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

type NamedEntitiesResponse struct {
	MediaID                *string `json:"mediaId,omitzero"`
	IsNamedEntitiesEnabled *bool   `json:"isNamedEntitiesEnabled,omitzero"`
}

func (n *NamedEntitiesResponse) GetMediaID() *string {
	if n == nil {
		return nil
	}
	return n.MediaID
}

func (n *NamedEntitiesResponse) GetIsNamedEntitiesEnabled() *bool {
	if n == nil {
		return nil
	}
	return n.IsNamedEntitiesEnabled
}
