/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
)

type PlaybackIDRequest struct {
	// Basic access policy for media content
	AccessPolicy *BasicAccessPolicy `default:"public" json:"accessPolicy"`
	// Controls access based on domains and user agents.
	AccessRestrictions *AccessRestrictions `json:"accessRestrictions,omitzero"`
}

func (p PlaybackIDRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlaybackIDRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlaybackIDRequest) GetAccessPolicy() *BasicAccessPolicy {
	if p == nil {
		return nil
	}
	return p.AccessPolicy
}

func (p *PlaybackIDRequest) GetAccessRestrictions() *AccessRestrictions {
	if p == nil {
		return nil
	}
	return p.AccessRestrictions
}
