/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
)

// PlaylistByIDResponseMetadata - Required when the playlist type is `smart`. Media created between `startDate` and `endDate` of `createdDate` is added. Optionally, you can include media based on `updatedDate`.
type PlaylistByIDResponseMetadata struct {
	// Date range with start and end dates.
	CreatedDate *DateRange `json:"createdDate,omitzero"`
	// Date range with start and end dates.
	UpdatedDate *DateRange `json:"updatedDate,omitzero"`
}

func (p PlaylistByIDResponseMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlaylistByIDResponseMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlaylistByIDResponseMetadata) GetCreatedDate() *DateRange {
	if p == nil {
		return nil
	}
	return p.CreatedDate
}

func (p *PlaylistByIDResponseMetadata) GetUpdatedDate() *DateRange {
	if p == nil {
		return nil
	}
	return p.UpdatedDate
}
