/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

type PlaylistByIDResponse struct {
	// Shows the request status. Returns true for success and false for failure.
	Success bool                     `json:"success"`
	Data    PlaylistByIDResponseData `json:"data"`
}

func (p *PlaylistByIDResponse) GetSuccess() bool {
	if p == nil {
		return false
	}
	return p.Success
}

func (p *PlaylistByIDResponse) GetData() PlaylistByIDResponseData {
	if p == nil {
		return PlaylistByIDResponseData{}
	}
	return p.Data
}

func (p *PlaylistByIDResponse) GetDataManual() *PlaylistByIDResponseDataManual {
	return p.GetData().PlaylistByIDResponseDataManual
}

func (p *PlaylistByIDResponse) GetDataSmart() *PlaylistByIDResponseDataSmart {
	return p.GetData().PlaylistByIDResponseDataSmart
}
