package components

// PlaybackIDDomains - Restrictions based on the originating domain of a request (e.g., whether requests from certain websites should be allowed or blocked).
type PlaybackIDDomains struct {
	// Policy action type
	DefaultPolicy *PolicyAction `json:"defaultPolicy,omitempty"`
	// A list of domains that are explicitly allowed access.
	Allow []string `json:"allow,omitempty"`
	// A list of domains that are explicitly blocked from accessing the resource.
	Deny []string `json:"deny,omitempty"`
}

func (p *PlaybackIDDomains) GetDefaultPolicy() *PolicyAction {
	if p == nil {
		return nil
	}
	return p.DefaultPolicy
}

func (p *PlaybackIDDomains) GetAllow() []string {
	if p == nil {
		return nil
	}
	return p.Allow
}

func (p *PlaybackIDDomains) GetDeny() []string {
	if p == nil {
		return nil
	}
	return p.Deny
}

// PlaybackIDUserAgents - Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
type PlaybackIDUserAgents struct {
	// Policy action type
	DefaultPolicy *PolicyAction `json:"defaultPolicy,omitempty"`
	// A list of specific user agents that are allowed to access the resource.
	Allow []string `json:"allow,omitempty"`
	// A list of specific user agents that are blocked.
	Deny []string `json:"deny,omitempty"`
}

func (p *PlaybackIDUserAgents) GetDefaultPolicy() *PolicyAction {
	if p == nil {
		return nil
	}
	return p.DefaultPolicy
}

func (p *PlaybackIDUserAgents) GetAllow() []string {
	if p == nil {
		return nil
	}
	return p.Allow
}

func (p *PlaybackIDUserAgents) GetDeny() []string {
	if p == nil {
		return nil
	}
	return p.Deny
}

// PlaybackIDAccessRestrictions - Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents.
type PlaybackIDAccessRestrictions struct {
	// Restrictions based on the originating domain of a request (e.g., whether requests from certain websites should be allowed or blocked).
	Domains *PlaybackIDDomains `json:"domains,omitempty"`
	// Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
	UserAgents *PlaybackIDUserAgents `json:"userAgents,omitempty"`
}

func (p *PlaybackIDAccessRestrictions) GetDomains() *PlaybackIDDomains {
	if p == nil {
		return nil
	}
	return p.Domains
}

func (p *PlaybackIDAccessRestrictions) GetUserAgents() *PlaybackIDUserAgents {
	if p == nil {
		return nil
	}
	return p.UserAgents
}

// PlaybackID - A collection of Playback ID objects utilized for crafting HLS playback urls.
type PlaybackID struct {
	// A unique identifier is generated by FastPix for the playbacks.
	ID *string `json:"id,omitempty"`
	// Access policy for media content
	AccessPolicy *AccessPolicy `json:"accessPolicy,omitempty"`
	// Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents.
	AccessRestrictions *PlaybackIDAccessRestrictions `json:"accessRestrictions,omitempty"`
}

func (p *PlaybackID) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PlaybackID) GetAccessPolicy() *AccessPolicy {
	if p == nil {
		return nil
	}
	return p.AccessPolicy
}

func (p *PlaybackID) GetAccessRestrictions() *PlaybackIDAccessRestrictions {
	if p == nil {
		return nil
	}
	return p.AccessRestrictions
}
