/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
)

// SimulcastUpdateResponseData - Displays the result of the request.
type SimulcastUpdateResponseData struct {
	// When you create the new simulcast, FastPix assign a universal unique identifier which can contain a maximum of 255 characters.
	SimulcastID *string `json:"simulcastId,omitzero"`
	// The RTMP hostname, combined with the application name, is crucial for connecting to third-party live streaming services and transmitting the live stream.
	URL *string `json:"url,omitzero"`
	// A unique stream key is generated for streaming, allowing the user to start streaming on any third-party platform using this key.
	StreamKey *string `json:"streamKey,omitzero"`
	// When set to false, the simulcast is disabled for the specified stream.
	IsEnabled *bool `json:"isEnabled,omitzero"`
	// You can search for videos with specific key value pairs using metadata, when you tag a video in "key":"value"s pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
	Metadata map[string]string `json:"metadata,omitzero"`
}

func (s SimulcastUpdateResponseData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SimulcastUpdateResponseData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SimulcastUpdateResponseData) GetSimulcastID() *string {
	if s == nil {
		return nil
	}
	return s.SimulcastID
}

func (s *SimulcastUpdateResponseData) GetURL() *string {
	if s == nil {
		return nil
	}
	return s.URL
}

func (s *SimulcastUpdateResponseData) GetStreamKey() *string {
	if s == nil {
		return nil
	}
	return s.StreamKey
}

func (s *SimulcastUpdateResponseData) GetIsEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.IsEnabled
}

func (s *SimulcastUpdateResponseData) GetMetadata() map[string]string {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// SimulcastUpdateResponse - Displays the result of the request.
type SimulcastUpdateResponse struct {
	// Shows the request status. Returns true for success and false for failure.
	Success *bool `json:"success,omitzero"`
	// Displays the result of the request.
	Data *SimulcastUpdateResponseData `json:"data,omitzero"`
}

func (s SimulcastUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SimulcastUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SimulcastUpdateResponse) GetSuccess() *bool {
	if s == nil {
		return nil
	}
	return s.Success
}

func (s *SimulcastUpdateResponse) GetData() *SimulcastUpdateResponseData {
	if s == nil {
		return nil
	}
	return s.Data
}
