/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

package components

import (
	"github.com/FastPix/fastpix-go/internal/utils"
)

type SimulcastRequest struct {
	// The RTMPS hostname, combined with the application name, is crucial for connecting to third-party live streaming services and transmitting the live stream.
	URL *string `default:"rtmp://example.com/" json:"url"`
	// A unique stream key is generated for streaming, allowing the user to start streaming on any third-party platform using this key.
	StreamKey *string `default:"d851d91d5b768b36k61a264dcc447b" json:"streamKey"`
	// You can search for videos with specific key-value pairs using metadata, when you tag a video in "key":"value" pairs.
	Metadata map[string]string `json:"metadata,omitzero"`
}

func (s SimulcastRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SimulcastRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SimulcastRequest) GetURL() *string {
	if s == nil {
		return nil
	}
	return s.URL
}

func (s *SimulcastRequest) GetStreamKey() *string {
	if s == nil {
		return nil
	}
	return s.StreamKey
}

func (s *SimulcastRequest) GetMetadata() map[string]string {
	if s == nil {
		return nil
	}
	return s.Metadata
}
